- ia32/a20.c
According to this document ([link](https://www.win.tue.nl/~aeb/linux/kbd/scancodes-11.html)) we should wait for kbd status register bit 0 to be set before every read (kbd output buffer full). On the other hand, we should wait for bit 1 to be cleared before every write (kbd input buffer empty).
> ia32: A20 - fixed waiting for keyboard

- ia32/low.h
- ia32/msg.c
- ia32/serial.c
- ia32/serial.h
- ia32/timer.c
- ia32/timer.h
- ia32/types.h
1. Enabled UART hardware FIFO.
2. Added support for high speed SCH311X UART.
3. Fixed timer_wait(). Added CPU cycles measurement.
> plo UART changes

- armv7m7-imxrt106x/serial.c
This PR is related to a similar change in imxrt-multi, which is/was discussed here https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/78
> imxrt106x: UART baudrate calculation based on sdk

- armv7m7-imxrt106x/serial.c
During debugging with jtag, when the processor is halted and receiving data with UART (e.g. keyboard typing on the console serial port)  - writing to the hardware FIFO (more characters than the FIFO size) causes the UART to overrun and locks it (until the  FIFO register is flushed and status flag is cleared by W1C), so no more data can be received after the processor is resumed - the attached commit resolves this problem, additionally adds clear status flags for noisy and framing errors.
A similar change is also added to the phoenix-rtos-devices/imxrt-multi (separate PR):
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/83
> imxrt106x: Add uart rx overrun, noisy and framing error handling

- armv7m7-imxrt106x/serial.c
Update: The rewriting of the rx error status flag handling seems to solve the nesting of noise / frame reset flags due to a possible race condition.
Due to the similarity, the changes also apply to: https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/86
> imxrt106x: Rewrite of uart RX error flags handling

- .github/workflows/ci.yml
> ci: add basic CI checks against phoenix-rtos-project

- cmd.c
- cmd.h
- devices/Makefile
- devices/flash-imxrt/Makefile
- devices/usbc-cdc/Makefile
- hal.h
- hal/armv7a/zynq7000/cmd.c
- hal/armv7a/zynq7000/config.h
- hal/armv7a/zynq7000/hal.c
- hal/armv7m/imxrt106x/config.h
- hal/armv7m/imxrt106x/hal.c
- hal/armv7m/imxrt117x/config.h
- hal/armv7m/imxrt117x/hal.c
- msg.c
- msg.h
- phfs.c
- phfs.h
- phoenixd.c
- phoenixd.h
- plo.c
- script.c
- script.h
Some of the commands were disable. They will be updated in the other PR.
> phfs: add new interface

- cmd.c
- cmd.h
- hal/armv7a/zynq7000/cmd.c
This PR should be started reviewing when [this one](https://github.com/phoenix-rtos/plo/pull/55) will be merged and `cmds` branch will be rebased.
> cmds: update to new interface of phfs

- cmds/echo.c
> cmds/echo: use lowercase; status is always showed

- cmds/cmd.c
> cmds/cmd: fixed array index out of bounds

- cmds/app.c
- corrected checking the number of arguments ( can be 4 or 5 )
- corrected length check of appname
> cmds/app: simplification of the code

- syspage.h
Change has been tested on imxrt106x.
> syspage: change program's name size

- cmds/copy.c
Copy command registers alias to file.
When user wants to copy program or file to storage, the alias to file will be added automatically.
JIRA: PD-124
> cmd/copy: register alias to file

- cmds/alias.c
- cmds/app.c
- cmds/bitstream.c
- cmds/call.c
- cmds/cmd.c
- cmds/cmd.h
- cmds/console.c
- cmds/copy.c
- cmds/dump.c
- cmds/echo.c
- cmds/go.c
- cmds/help.c
- cmds/kernel.c
- cmds/map.c
- cmds/phfs.c
- cmds/script.c
- cmds/syspage.c
- cmds/wait.c
- lib/ctype.c
- lib/ctype.h
This PR introduces a change to the way arguments are passed to plo command line programs, the convention introduced in this PR is similar to the standard C `main` function, arguments are passed to commands using `int argc, const char *argv[]` construct.
> Change the script and command parser to accept arguments like in C  `main(argc, argv)`

- cmds/console.c
This PR fixes an incorrect argument number with information about an incorrect minor value.
> cmds/console: argument number corrected

- cmds/Makefile
- cmds/mpu.c
- hal/armv7a/zynq7000/hal.c
- hal/armv7m/Makefile
- hal/armv7m/imxrt/10xx/Makefile
- hal/armv7m/imxrt/10xx/config.h
- hal/armv7m/imxrt/10xx/hal.c
- hal/armv7m/imxrt/10xx/imxrt.c
- hal/armv7m/imxrt/10xx/imxrt.h
- hal/armv7m/imxrt/117x/Makefile
- hal/armv7m/imxrt/117x/config.h
- hal/armv7m/imxrt/117x/hal.c
- hal/armv7m/imxrt/types.h
- hal/armv7m/mpu.c
- hal/armv7m/mpu.h
- hal/hal.h
- syspage.c
- syspage.h
JIRA: RTOS-2
Setup MPU regions using plo script `map` command.
Use the best fit method for region allocation
(split difficult to align regions into sub regions
whenever it is possible to optimize MPU region usage)
greedily configure the largest possible part of the
given region from the base address.
MPU setup is prepared in `plo`, region setup is forwarded
in syspage to `phoenix-rtos-kernel` with each region
multi-map configuration is linked, the `phoenix-rtos-kernel`
is responsible to enable the MPU in priviledged mode.
to verify on i.MX RT1064 use the following map setup for script.plo:
```
map itcm 0x0 0x58000 rwx
map dtcm 0x20000000 0x20028000 rwx
map ocram2 0x20200000 0x20280000 rwxc
map aips14 0x40000000 0x40400000 rws
map aips05 0x42000000 0x42100000 rws
map xip2 0x60000000 …
```
> hal: add MPU setup based on map configuration

- cmds/bitstream.c
- cmds/kernel.c
- devices/flash-imxrt/flashcfg.c
- devices/flash-imxrt/flashcfg.h
- hal/armv7a/zynq7000/config.h
- hal/armv7a/zynq7000/hal.c
- hal/armv7m/imxrt/10xx/config.h
- hal/armv7m/imxrt/10xx/hal.c
- hal/armv7m/imxrt/117x/config.h
- hal/armv7m/imxrt/117x/hal.c
- syspage.c
Changed names of some defines.
Paweł asked to change names of those defines.
[JIRA: PD-142](https://jira.phoenix-rtos.com/browse/PD-142)
> Keep consistent defines naming scheme

- cmds/kernel.c
Added finding ELF sections by name in order to set them correctly in syspage.
[JIRA: PD-150](https://jira.phoenix-rtos.com/browse/PD-150)
> cmds/kernel.c: add finding ELF sections by name

- cmds/app.c
- cmds/call.c
- cmds/kernel.c
- cmds/map.c
- cmds/script.c
- devices/devs.c
- devices/devs.h
- devices/flash-imxrt/flashdrv.c
- devices/uart-imxrt106x/uart.c
- devices/uart-imxrt117x/uart.c
- devices/uart-zynq7000/uart.c
- devices/usbc-cdc/cdc.c
- devices/usbc-cdc/client.c
- devices/usbc-cdc/usbclient.h
- hal/armv7a/string.h
- hal/armv7m/string.h
- phfs/phfs.c
- phfs/phfs.h
- phfs/phoenixd.c
- phfs/phoenixd.h
- syspage.c
- syspage.h
Changed plo standard functions signatures to resemble their standard C library equivalents.
The interface is cleaner. Some type casting is no longer necessary.
[JIRA: PD-141](https://jira.phoenix-rtos.com/browse/PD-141)
> Clean up standard functions interface

- devices/disk-bios/Makefile
- devices/disk-bios/disk-bios.c
- devices/tty-bios/Makefile
- devices/tty-bios/tty-bios.c
- devices/uart-16550/Makefile
- devices/uart-16550/uart-16550.c
- devices/uart-16550/uart-16550.h
- devices/uart-16550/uarthw-pc.c
- devices/uart-16550/uarthw-riscv.c
- devices/uart-16550/uarthw.h
- hal/ia32/Makefile
- hal/ia32/_exceptions.S
- hal/ia32/_init.S
- hal/ia32/_interrupts.S
- hal/ia32/config.h
- hal/ia32/console-serial.c
- hal/ia32/console-vga.c
- hal/ia32/cpu.c
- hal/ia32/cpu.h
- hal/ia32/exceptions.c
- hal/ia32/hal.c
- hal/ia32/interrupts.c
- hal/ia32/memory.c
- hal/ia32/peripherals.h
- hal/ia32/string.c
- hal/ia32/string.h
- hal/ia32/timer.c
- hal/ia32/types.h
New plo version for ia32-generic target.
[JIRA: PD-97](https://jira.phoenix-rtos.com/browse/PD-97)
[Clean up standard functions interface](https://github.com/phoenix-rtos/plo/pull/106)
[Keep consistent defines naming scheme](https://github.com/phoenix-rtos/plo/pull/107)
> hal/ia32: new ia32 plo version

- syspage.c
Moved syspage_hal_t field on top of syspage_t struct.
Change required by new plo for ia32. For more details check JIRA link below:
[JIRA: PD-153](https://jira.phoenix-rtos.com/browse/PD-153)
[hal/syspage: move syspage_hal_t field on top of syspage_t struct #212](https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/212)
> syspage.c: move syspage_hal_t field on top of syspage_t struct

- hal/armv7a/zynq7000/hal.c
- hal/armv7m/imxrt/10xx/hal.c
- hal/armv7m/imxrt/117x/hal.c
- hal/hal.h
- hal/ia32/cpu.c
Changed hal_cpuJump() return type to void + marked it as 'noreturn'.
[JIRA: PD-159](https://jira.phoenix-rtos.com/browse/PD-159)
> hal: mark hal_cpuJump() function as noreturn

- hal/ia32/Makefile
- hal/ia32/console-vga.c
- hal/ia32/memory.c
- hal/ia32/peripherals.h
- lib/sprintf.c
Final changes required for enabling new plo for ia32.
[JIRA: PD-97](https://jira.phoenix-rtos.com/browse/PD-97)
> hal/ia32: disable UART_GALILEO due to lack of correct device detection + small code improvements

- cmds/Makefile
- cmds/alias.c
- hal/armv7m/imxrt/10xx/Makefile
- hal/armv7m/imxrt/10xx/_init.S
- hal/armv7m/imxrt/10xx/config.h
- hal/armv7m/imxrt/10xx/hal.c
- hal/armv7m/imxrt/types.h
- hal/armv7m/mpu.c
- hal/armv7m/mpu.h
- hal/hal.h
- lib/list.c
- lib/list.h
- phfs/phfs.c
- phfs/phfs.h
- plo.c
- syspage.c
- syspage.h
The PR consists the following changes:
- change `dev_map` interface - entries have been introduced in new syspage structure and `addr_t *a` is no longer needed,
- update phfs interface,
- remove any references in hal to the upper layers,
- remove `syspage` command,
- new syspage structure which should be applied to other platform - more details in commit message.
**NOTE:**
If these changes will be accepted I will update the rest of the platforms and commands. Currently, only `imxrt106x hal` is updated.
I would like to discuss new syspage structure whether it is applicable for other platforms.
> plo: new syspage structure 

- hal/armv7a/zynq7000/_init.S
- hal/armv7a/zynq7000/config.h
- hal/armv7a/zynq7000/cpu.h
- hal/armv7a/zynq7000/hal.c
- hal/armv7a/zynq7000/interrupts.c
- hal/armv7a/zynq7000/types.h
- hal/armv7m/imxrt/117x/_init.S
- hal/armv7m/imxrt/117x/config.h
- hal/armv7m/imxrt/117x/hal.c
Adapt new syspage approach to hal on zynq7000 and imxrt117x.
Moreover, errno has been removed from hal/arm*.
**NOTE!!**
This PR will work after providing changes in commands which will be added in the next PR. Merge is done to temporary branch -`feature/syspage`.
The changes have been broken down into smaller ones to limit the code size to review.
> plo: update hal/imxrt117x and hal/zynq7000 after changes in syspage

- syspage.c
JIRA: PD-170
If data is not aligned to 4, there is exception abort interrupt.
Data in syspage structure is packed so operations use in `LIST_ADD` macro might lead to undefined behavior. For this reason, list implementation from lib is not used anymore in syspage.
> syspage: align data in syspage's heap to 4 and don't use LIST_ADD

- devices/uart-imx6ull/Makefile
- devices/uart-imx6ull/uart.c
- lib/Makefile
- lib/cbuffer.c
- lib/cbuffer.h
- lib/lib.h
- add circular buffer
- add uart-imx6ull
> plo: add uart-imx6ull

- cmds/Makefile
- cmds/test-ddr.c
- hal/armv7a/imx6ull/Makefile
- ddr test is derived from https://github.com/phoenix-rtos/phoenix-rtos-kernel/blob/master/hal/armv7a/memtest.c - some small modification has been made,
- tested on `imx6ull` and `zynq7000` - both passed
**NOTE!!!**
I am not well familiarized with DDR controller so I am not sure whether basic setting related to `BANK_COUNT`, `COLUMN_COUNT` and `ROW_COUNT` can be applicable to memories with different size. 
Previously code works on `imx6ull` so that this command should be added to this platform. However, I have doubts related to `zynq7000`. @agkaminski, what do you think?
Use command instead of building bare-metal test.
> plo: add ddr test

- devices/usbc-cdc/usbphy-imx6ull.c
- devices/usbc-cdc/usbphy-imxrt106x.c
- devices/usbc-cdc/usbphy-zynq7000.c
- devices/usbc-cdc/usbphy.h
- hal/armv7a/imx6ull/config.h
- draft of usbphy-imx6ull 
- reduction of memory usage
> plo: add usbphy-imx6ull and reduce memory usage

- devices/uart-imxrt106x/uart.c
- devices/uart-zynq7000/uart.c
- add cbuffer implementation to uart-zynq7000 and uart-imxrt106x
- change BUFFER_SIZE to reduce usage of .bss
- fix data transmission on zynq 7000 - according to RM, irq status should not be cleared after transmission
> plo: add cbuffer to uart-imxrt106x and uart-zynq7000

- hal/armv7m/Makefile
- hal/armv7m/string.c
- hal/armv7m/string.h
JIRA: PD-180
Remove static inline functions in a string unit
Saved more that 2kB.
> plo/armv7m: remove static inline functions in a string unit

- hal/armv7m/imxrt/10xx/imxrt.c
- hal/armv7m/imxrt/117x/_init.S
- hal/armv7m/imxrt/117x/imxrt.c
- hal/armv7m/imxrt/117x/imxrt.h
> imxrt: Fix sleep config, addded missing bariers

- devices/flash-zynq7000/Makefile
- devices/flash-zynq7000/flashcfg.c
- devices/flash-zynq7000/flashcfg.h
- devices/flash-zynq7000/flashdrv.c
- devices/flash-zynq7000/qspi.c
- devices/flash-zynq7000/qspi.h
The following changes have been made:
- Quad-SPi controller driver implementation,
- getting flash configuration based on CFI (Common Flash Interface) which is get via RDID command,
- nor flash driver implementaion  using qspi.
JIRA: PD-200
Needed for booting zynq7000 from nor flash.
> flash-zynq7000: add nor flash driver

- hal/armv7a/imx6ull/config.h
- hal/armv7a/imx6ull/types.h
- hal/armv7a/zynq7000/Makefile
- hal/armv7a/zynq7000/config.h
- hal/armv7a/zynq7000/types.h
- hal/armv7m/imxrt/10xx/config.h
- hal/armv7m/imxrt/117x/config.h
- hal/armv7m/imxrt/types.h
- hal/armv7m/mpu.c
- hal/armv7m/mpu.h
- hal/hal.h
- plo.c
- syspage.c
- syspage.h
In the new syspage approach, the syspage headres are moved to **phoenix-rtos-kernel/includes/syspage*.h**.
JIRA: PD-6
> plo: update syspage's headers paths

- syspage.c
> syspage: fix map iteration in cyclic list in syspage_entryAdd

- devices/usbc-cdc/usbphy-imx6ull.c
> usbphy-imx6ull: use consistent naming of memory pools

- hal/armv7m/cpu.c
- hal/armv7m/imxrt/117x/imxrt.c
Some functions invocation haven't been changed in the previous commits, it caused compilation errors.
JIRA: PD-182
> hal/armv7m/117x: fix invocation of undeclared functions

- hal/armv7a/string.c
- hal/armv7m/string.c
- hal/ia32/exceptions.c
- hal/ia32/string.c
- hal/string.h
Make consistent interface and implementation with kernel's string functions.
The functions are copied from kernel.
Changes are provided to avoid errors resulting from different implementations of the same things.
> hal/string: make consistent interface with phoenix-rtos-kernel/hal/string

- devices/flash-imxrt/flashcfg.c
- devices/flash-imxrt/flashcfg.h
- hal/armv7m/imxrt/10xx/console.c
- hal/armv7m/imxrt/117x/console.c
Merge master branch into feature/syspage.
> merge master to feature/syspage

- devices/flash-zynq7000/flashdrv.c
Fixed:
- wrong region size calulation,
- wrong offset calculation in flashdrv_write (used chunkSz insted of saveSz)
JIRA: PD-219
> flashdrv-zynq7000: fix bugs discovered after testing driver in user-space

- devices/flash-zynq7000/flashcfg.c
- devices/flash-zynq7000/flashcfg.h
- devices/flash-zynq7000/flashdrv.c
- devices/flash-zynq7000/qspi.c
> zynq7000-flash: code refactoring to be consistent with driver in user space

- hal/armv7m/stm32/hal.c
- hal/armv7m/stm32/l4/Makefile
Add reboot command on stm32l4 targets
JIRA: RTOS-164
> armv7m/stm32l4: Add reboot on stm32l4 target

- syspage.c
Now if the `syspage_alloc()` function returns `NULL` a `NULL` value is returned which is `OK`.
> syspage_mapAdd: fix error return value

- Makefile
JIRA: RTOS-173
This change improves:
* concurrent builds (local using standard `CC=*-phoenix-gcc` and networked using `CC=distcc`)
* incremental build/gen. of linker scripts
* add directory guards (as prerequisite)
This PR fixes random CI issue:
https://github.com/phoenix-rtos/phoenix-rtos-project/runs/5678692510?check_suite_focus=true
> makes: Improve concurent build of ld scripts

- cmds/cmd.h
> cmds: increase command's line size

- ld/armv7a9-zynq7000.ldt
to avoid kernel/apps overwrite
JIRA: PP-19
> zynq: Moved bitstream buffer to the DDR memory end

- cmds/call.c
> cmds/call: Continue script execution, when MAGIC mismatches

- devices/flash-zynq7000/flashcfg.c
Add new flash memory device.
PP-34
> flash-zynq7000: add Winbond W25Q128JV NOR flash memory

- Makefile
[JIRA: PP-17](https://jira.phoenix-rtos.com/browse/PP-17)
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/413
> Adapt to projects build changes

- cmds/Makefile
- hal/armv7a/zynq7000/Makefile
- hal/armv7a/zynq7000/zynq.c
- configure DDR based on parameters in board_config.h ,
- add test-ddr for zynq7000 target
> hal/zynq7000: configure DDR based on parameters in board_config.h 

- Makefile
[JIRA: RTOS-199](https://jira.phoenix-rtos.com/browse/RTOS-199)
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/423
> Adapt to projects artifacts directory changes

- devices/uart-zynq7000/uart.c
- hal/armv7a/zynq7000/console.c
- hal/armv7a/zynq7000/peripherals.h
> zynq7000/uart: Use board_config.h definitions

- devices/flash-flexspi/flashdrv.c
JIRA: NIL-299
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/262
> flash-flexspi: improve write of the last sector

- devices/uart-imxrt106x/uart.c
- devices/uart-imxrt117x/uart.c
- hal/armv7m/imxrt/10xx/_init.S
- hal/armv7m/imxrt/117x/_init.S
- hal/armv7m/interrupts.c
> imxrt: Fix interupt handlers and dispatchers section assignments.

- cmds/Makefile
- cmds/bankswitch.c
- cmds/cmd.h
- hal/armv7m/stm32/l4/Makefile
- hal/armv7m/stm32/l4/_init.S
- hal/armv7m/stm32/l4/stm32l4.c
- hal/armv7m/stm32/l4/stm32l4.h
- ld/armv7m4-stm32l4x6.ldt
Add bank switching command and copy plo to RAM (to allow bank switching during plo execution).
To use this feature you need to have second FW in the second flash bank (along with user script) and in the preinit script do:
```
call user.plo
bankswitch
call user.plo
```
This will cause flash bank remapping and second FW boot should first FW's user scipt magic be invalid.
To allow upgrade feature on this target
> STM32L4: Dual bank/script FW selection in plo

- hal/armv7a/zynq7000/Makefile
- hal/armv7a/zynq7000/hal.c
- hal/armv7a/zynq7000/zynq.c
- hal/armv7a/zynq7000/zynq.h
> hal/arm7a9-zynq7000: add software reset

- devices/flash-flexspi/flashdrv.c
> flash-flexspi: Invalidate sync buffer if it's out of range

- devices/flash-zynq7000/flashcfg.c
- devices/flash-zynq7000/qspi.c
- increase frequency to 100 MHz and configure feedback clock
- increase region size to speed up flashing process
PP-278
> flash-zynq7000: increase clock freq & speed up flashing process

- devices/flash-zynq7000/qspi.c
> zynq-7000/qspi: configure qspi pins based on board_config data

- devices/devs.c
- devices/devs.h
- devices/ram-stm32/Makefile
- devices/ram-stm32/ramdrv.c
- hal/armv7m/stm32/l4/Makefile
- hal/armv7m/stm32/l4/peripherals.h
- ld/armv7m4-stm32l4x6.ldt
- devices: stm32l4x6: add ram storage driver based on flash-stm32
- stm32l4x6: move FLASH defines from hal to linker template
- It's needed for loading apps, previously placed in RAM memory (for example by gdb and jtag). Required for stm32l4x6-nucleo testing process.
- JIRA: PD-301
- Memory areas should be located in linker script
- JIRA: RTOS-245
> devices: stm32l4x6: add ram storage driver based on flash-stm32

- devices/usbc-cdc/usbphy-imx6ull.c
- hal/armv7a/Makefile
- hal/armv7a/_cache.S
- hal/armv7a/cache.h
- hal/armv7a/imx6ull/_init.S
- hal/armv7a/imx6ull/hal.c
- hal/armv7a/mmu.c
- hal/armv7a/mmu.h
- ld/armv7a7-imx6ull.ldt
- define cached an uncached memories in the linker script
- add MMU controller for `armv7a`
- MMU is enabled for `imx6ull`
- MMU is disabled and cache is flushed and disabled before jump to kernel
- cache management module is added
- as an example, USB buffers are placed in `uncached_ddr`
MMU is enabled to allow allocation of uncached memory.
> hal/armv7a/imx6ull: enable MMU for linear addresses translations

- devices/usbc-cdc/usbphy-zynq7000.c
- hal/armv7a/imx6ull/hal.c
- hal/armv7a/zynq7000/hal.c
- ld/armv7a9-zynq7000.ldt
Enable MMU for zynq7000 targets.
> zynq7000: enable MMU

- hal/armv7a/imx6ull/hal.c
- hal/armv7a/zynq7000/hal.c
> hal/armv7a: add missing plo sections to map entries

- hal/armv7a/_cache.S
Changes:
- removed unnecessary `it` instruction in `arm` mode ( `as` removes this instruction )
- deleted double instruction `bx lr`
> hal/armv7a/_cache.S: minor code cleaning

- hal/armv7a/_cache.S
- hal/armv7a/cache.h
Changes:
- using `ubfx`
- changed `mov` to `lsl` ( it is prefered in that case )
- in function `hal_dcacheInvalAll()` use of register incrementation by `1 << 30` instead of by `1`.
- since the `hal_dcacheEnable()` and the `hal_icacheEnable()` functions differ only in the mask value, a local function `cacheEnable()` was defined to which the mask value in `r1` register is passed
- cache.h : added a missing `hal_dcacheInvalAll(void)` declaration
Do these functions need to be written in assembler?
> hal/armv7a/_cache.S: code improvement

- Makefile
> make: use explicit `PLO_SCRIPT_DIR`

- devices/uart-zynq7000/uart.c
If fifo is empty the IRQ is not invoked. 
For this reason, additional condition is added to handle this situation. 
Fixes: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/495
RTOS-265
> zynq7000-uart: fix writing data

- hal/armv7m/interrupts.c
Fixed NVIC being set for SCB handled exception (systick) on armv7m.
> Interrupts bug-fix

- devices/flash-zynq7000/flashdrv.c
- hal/armv7a/zynq7000/Makefile
Add erase handler implementation.
`jffs2` partition needs to be erased before writing a new filesystem. 
RTOS-273
> zynq7000-flash: add erase handler implementation

- cmds/dump.c
- syspage.c
- syspage.h
Extends the functionality of the memory content analysis tool. Performs `memory range checking` against defined maps and whether the `read attribute is set`. If the memory range given in the arguments for the `dump` command is incorrect, or no read access is available, or the maps are not defined at all, the command will display masked octet value `XX` for the given range.
Additionally the selected range is printed starting form alignment down to 16 bytes + offset.
When used with flag `-F` memory map validation is disabled (than works like the earlier implementation).
An additional option is to read disks `ia32`  hard disk or floppy disk, on `imxrt-flexspi` via IP Bus it reads NOR memory, utilizing `phfs` subsystem.
Example on ia32: `dump -r hd0 0 100` prints 100 bytes from the beginning …
> Extend functionality of debug command and memory map attributes check.

- cmds/app.c
- devices/flash-flexspi/flashdrv.c
- devices/flash-stm32/flashdrv.c
- syspage.h
JIRA: RTOS-267
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/536
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/158
https://github.com/phoenix-rtos/plo/pull/215
https://github.com/phoenix-rtos/libphoenix/pull/210
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/348
> cmd/app: Add -xn option (don't load elf to map)

- cmds/cmd.c
> cmds: handle lf as newline character

- devices/flash-nrf9160/Makefile
- devices/flash-nrf9160/flashdrv.c
- devices/uart-nrf9160/Makefile
- devices/uart-nrf9160/uart.c
- hal/armv8m/Makefile
- hal/armv8m/cpu.c
- hal/armv8m/cpu.h
- hal/armv8m/interrupts.c
- hal/armv8m/mpu.c
- hal/armv8m/mpu.h
- hal/armv8m/nrf/91/Makefile
- hal/armv8m/nrf/91/_init.S
- hal/armv8m/nrf/91/config.h
- hal/armv8m/nrf/91/console.c
- hal/armv8m/nrf/91/nrf91.c
- hal/armv8m/nrf/91/nrf91.h
- hal/armv8m/nrf/91/peripherals.h
- hal/armv8m/nrf/91/timer.c
- hal/armv8m/nrf/Makefile
- hal/armv8m/nrf/hal.c
- hal/armv8m/nrf/types.h
- hal/armv8m/string.c
- ld/armv8m33-nrf9160.ldt
- add armv8m33-nrf9160 port
New architecture available in Phoenix-RTOS project
> add armv8m33-nrf9160 port

- ld/armv7m7-imxrt106x.ldt
> imxrt106x: Add support for custom FlexRAM config

- devices/flash-flexspi/nor/nor.c
> flash-flexspi: Add W25Q256JVEIQ nor flash

- devices/flash-flexspi/flashdrv.c
- devices/flash-flexspi/fspi.h
- devices/flash-flexspi/fspi/fspi.c
- devices/flash-flexspi/fspi/fspi_rt105x.h
- devices/flash-flexspi/fspi/fspi_rt106x.h
- devices/flash-flexspi/fspi/fspi_rt117x.h
> flash-flexspi: fix AHB read and returned data size

- cmds/Makefile
- cmds/dump.c
- cmds/test-dev.c
- hal/armv7a/imx6ull/Makefile
- lib/console.c
- lib/console.h
JIRA: RTOS-382
Simple read write erase testing utility.
During developing plo drivers it's hard to test if they actually work.
> cmds: implement test-dev

- devices/flash-imx6ull/Makefile
- devices/flash-imx6ull/flashdrv.c
- devices/flash-imx6ull/lut.h
- devices/flash-imx6ull/nor/flash.h
- devices/flash-imx6ull/nor/nor.c
- devices/flash-imx6ull/nor/nor.h
- devices/flash-imx6ull/nor/nor_lut.h
- devices/flash-imx6ull/nor/nor_mx.c
- devices/flash-imx6ull/qspi.h
- devices/flash-imx6ull/qspi/qspi.c
- hal/armv7a/imx6ull/Makefile
JIRA: RTOS-319
imx6ull-flashnor qspi driver
This driver is almost copy paste of flash-flexspi with fspi module changed to qspi.
imx6ull lacks proper plo, flash driver is a needed milestone to implement it.
> imx6ull: nor-driver qspi

- hal/ia32/hal.c
- hal/ia32/memory.c
- Fix **plo** being stuck in an infinite loop, trying to enable A20 line, if A20 is enabled and there is no 8042 keyboard controller.
- Fix **plo** being stuck in an infinite loop, trying to enable A20 line, if A20 is disabled and there is no 8042 keyboard controller.
- Add an error message, when **plo** fails to enable A20 line.
DONE: RTOS-305
**plo** didn't start the kernel on some hardware
> hal/ia32: Fix kernel not starting on some hardware

- cmds/dump.c
> cmds/dump: change parsing of start arg

- cmds/test-dev.c
> cmds/test-dev: fix output on discrepency

- devices/uart-imxrt106x/uart.c
- devices/uart-imxrt117x/uart.c
> imxrt: Add board_config to uart.c

- hal/armv7a/imx6ull/types.h
- hal/armv7a/zynq7000/types.h
- hal/armv7m/imxrt/types.h
- hal/armv7m/stm32/types.h
> Remove duplicated typedefs.

- cmds/copy.c
- phfs/msg.h
- phfs/phfs.h
- phfs/phoenixd.c
JIRA: RTOS-459
Writing to host deviceis a lacking feature that will be usefull for debugging.
> phoenixd: implement write

- devices/flash-imx6ull/qspi/qspi.c
- hal/armv7a/imx6ull/_init.S
> imx6ull: speedup qspi clock

- cmds/bootcm4.c
- hal/armv7m/cpu.c
- hal/armv7m/cpu.h
* fixes dcache coherency between CM7-CM4 cores after load CM4 image.
* add functions to clean dcache by address, clean & invalidate dcache by address
> Fix bootcm4 cache coherency between CM4-CM7 cores

- devices/devs.c
- devices/devs.h
- devices/nand-imx6ull/Makefile
- devices/nand-imx6ull/data.c
- devices/nand-imx6ull/data.h
- devices/nand-imx6ull/drv.c
- devices/nand-imx6ull/drv.h
- devices/nand-imx6ull/meta.c
- devices/nand-imx6ull/raw.c
- hal/armv7a/imx6ull/Makefile
- hal/armv7a/imx6ull/_init.S
- hal/armv7a/imx6ull/hal.c
- hal/armv7a/imx6ull/imx6ull.c
- ld/armv7a7-imx6ull.ldt
JIRA: DTR-322
Introduces 3 new device types:
DEV_NAND_DATA - for data only buffered accesses
DEV_NAND_META - for modifying metadata with unbuffered accesses.
DEV_NAND_RAW - for data + meta unbuffered accesses
Needed to support plo on DTR.
> imx6ull: nand support

- devices/flash-flexspi/flashdrv.c
- devices/flash-imx6ull/flashdrv.c
> flashdrv: fix erased sector buffer check (imx targets)

- devices/flash-imx6ull/flashdrv.c
- devices/flash-imx6ull/nor/nor.c
- devices/usbc-cdc/usbphy-zynq7000.c
> flash-imx6ull: Print flash info at init

- lib/getopt.c
Change is in consequence of (is analogous to) https://github.com/phoenix-rtos/libphoenix/pull/267
JIRA: RTOS-511
> update getopt to libphoenix/unistd pull-request

- hal/armv7a/zynq7000/Makefile
Switch from erase to `jffs2 -e -c` in CI in order to set clean markers at once and make erasing process more efficient.
JIRA: RTOS-515
> hal: enable jffs2 command for zynq7000

- hal/armv7m/exceptions.c
Changes logic to that in phoenix-rtos-kernel after recent changes e.g.:
[phoenix-rtos-kernel/.../armv7m](https://github.com/phoenix-rtos/phoenix-rtos-kernel/blob/93a1bf1eea8991eab40f92bef05b0423559b284e/hal/armv7m/exceptions.c#L101-L107)
[phoenix-rtos-kernel/.../ia32](https://github.com/phoenix-rtos/phoenix-rtos-kernel/blob/93a1bf1eea8991eab40f92bef05b0423559b284e/hal/ia32/exceptions.c#L194-L201)
JIRA: RTOS-520
> armv7m: Change cpuReset logic in exceptions

- devices/uart-gr716/uart.c
- hal/sparcv8leon3/gr716/console.c
- hal/sparcv8leon3/gr716/gr716.c
- hal/sparcv8leon3/gr716/gr716.h
> gr716: remove unnecessary gpio configuration

- cmds/Makefile
- cmds/mem.c
- hal/armv7a/imx6ull/Makefile
- hal/armv7a/zynq7000/Makefile
- hal/armv7m/imxrt/10xx/Makefile
- hal/armv7m/imxrt/117x/Makefile
- hal/armv7m/stm32/l4/Makefile
- hal/armv8m/nrf/91/Makefile
- hal/ia32/Makefile
- hal/ia32/cpu.h
- hal/sparcv8leon3/gr716/Makefile
The `mem` command provides the ability to test physical memory adresss space, `mem` tool reads and writes memory cells. When it comes to physical memory space inspection (read), it differs from the `dump` command in that the reading is performed by specifying the size of the word, not bytes, and values are read as integers of specified width machine order. Additionally memory alignment may be specified, it checks addresses with `plo` memory map definitions (to disable use `-F` switch).
read 32bit word from `0x7c00` address
```bash
(plo)% mem -r -- 0x7c00
```
*note `--` may be skipped, is optional to separate options/switches from the physical address
write `0xdeadc0de` value at `0x7c00` address
```bash
(plo)% mem -w 0xdeadc0de -- 0x7c00
```
write 256 `ff's`  starting from `0x20020000` …
> cmds: implement `mem` read/write tool

- hal/sparcv8leon3/_init.S
- hal/sparcv8leon3/cpu.c
- hal/sparcv8leon3/gr716/gr716.c
- hal/sparcv8leon3/gr716/gr716.h
> gr716: fix SPI boot

- cmds/Makefile
- cmds/lspci.c
- hal/ia32/Makefile
- hal/ia32/pci.c
- hal/ia32/pci.h
Adds `lspci` command and hal functions to access PCI bus configuration data.
qemu-generic (with ac97 codec)
real hardware: Intel BX440 PII
real hardware: S3 Virge SVGA Display device details (MMIO at 0xe0000000, BAR @ 0x10)
Dev tools, and debugging.
JIRA: RTOS-595
> ia32: pci bus device enumerating tool

- Makefile
- hal/armv7a/imx6ull/Makefile
- hal/armv7a/zynq7000/Makefile
- hal/armv7m/imxrt/10xx/105x/Makefile
- hal/armv7m/imxrt/10xx/106x/Makefile
- hal/armv7m/imxrt/117x/Makefile
- hal/armv7m/stm32/l4/Makefile
- hal/armv8m/nrf/91/Makefile
- hal/sparcv8leon3/gr716/Makefile
JIRA: CI-344
CI to pass: https://github.com/phoenix-rtos/phoenix-rtos-project/pull/834
> make: switch to linking by gcc

- hal/sparcv8leon3/gr716/Makefile
> gr716: fix filter-out linker flags

- hal/sparcv8leon3/gr716/config.h
> gr716: use SYSCLK_FREQ defined in board_config

- hal/armv7m/stm32/l4/stm32l4.c
JIRA: DEND-32
Provide a possibility to enable/disable watchdog without BOARD_CONFIG env
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/847
https://github.com/phoenix-rtos/plo/pull/293
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/453
https://github.com/phoenix-rtos/phoenix-rtos-build/pull/163
> stm32l4x6: Enable watchdog independently of NDEBUG

- devices/disk-bios/disk-bios.c
- hal/ia32/_init.S
- hal/ia32/memory.c
- ld/common/plo-ia32.lds
- ld/ia32-generic.ldt
> IA32 port fixes

- cmds/jffs2.c
> jffs2: log progress

- cmds/jffs2.c
JIRA: RTOS-660
Before change :
After:
> jffs2: fix log output

- hal/ia32/acpi.c
JIRA: RTOS-530
Change in plo that is required for https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/476 to work.
> hal/ia32: Add HPET

- devices/sdcard-zynq7000/Makefile
- devices/sdcard-zynq7000/sdcard.c
- devices/sdcard-zynq7000/sdcard.h
- devices/sdcard-zynq7000/sdcarddrv.c
- devices/sdcard-zynq7000/sdhost_defs.h
- devices/sdcard-zynq7000/zynq7000-sdio.c
- devices/sdcard-zynq7000/zynq7000-sdio.h
- hal/armv7a/zynq7000/Makefile
- hal/armv7a/zynq7000/zynq.c
- hal/armv7a/zynq7000/zynq.h
Added SD card storage driver to PLO. 
Driver allows data to be read and written to the SD card. It supports SD and SDHC/SDXC cards of any size, but due to limitations of PLO on this platform only the first 4 GB of the card are accessible. 
Byte-wise reads and writes are allowed, but doing operations not aligned to 512 byte blocks is inefficient because no caching is performed. In case of unaligned writes, each operation results in a read-modify-write cycle which can put unnecessary wear on the card.
Driver expects the SD card to be inserted at startup and does not re-try initialization.
> zynq7000: add SD card storage driver

- devices/flash-gr712rc/Makefile
- devices/flash-gr712rc/cmds.h
- devices/flash-gr712rc/flash.c
- devices/flash-gr712rc/flash.h
- devices/flash-gr712rc/flashdrv.c
- devices/flash-gr712rc/ftmctrl.h
- hal/sparcv8leon3/cpu.h
- hal/sparcv8leon3/gaisler/gr712rc/Makefile
- hal/sparcv8leon3/gaisler/gr712rc/config.h
- hal/sparcv8leon3/gaisler/gr712rc/hal.c
> gr712rc: implement flash driver

- hal/sparcv8leon3/string.c
> sparcv8leon3: fix hal_strncpy implementation

- lib/crc32.c
> lib/crc32: make calculation consistent with filesystems

- cmds/alias.c
JIRA: RTOS-713
Fixes https://github.com/phoenix-rtos/plo/pull/310#issuecomment-1870175963
> cmd/alias: Fix log's usage of argv

- cmds/erase.c
- devices/devs.c
- devices/devs.h
- devices/pipe-rtt/Makefile
- devices/pipe-rtt/device.c
- devices/pipe-rtt/rtt.c
- devices/pipe-rtt/rtt.h
- hal/armv7a/imx6ull/console.c
- hal/armv7a/zynq7000/console.c
- hal/armv7m/imxrt/10xx/105x/Makefile
- hal/armv7m/imxrt/10xx/106x/Makefile
- hal/armv7m/imxrt/10xx/106x/peripherals.h
- hal/armv7m/imxrt/10xx/console.c
- hal/armv7m/imxrt/117x/Makefile
- hal/armv7m/imxrt/117x/console.c
- hal/armv7m/imxrt/117x/peripherals.h
- hal/armv7m/imxrt/hal.c
- hal/armv7m/stm32/hal.c
- hal/armv7m/stm32/l4/Makefile
- hal/armv7m/stm32/l4/console.c
- hal/armv8m/nrf/91/console.c
- hal/hal.h
- hal/ia32/console-serial.c
- hal/ia32/console-vga.c
- hal/sparcv8leon3/gaisler/console.c
- lib/console.c
- lib/console.h
- lib/prompt.c
- lib/prompt.h
`Real Time Transfer`, a.k.a. `RTT` is an interface specified by SEGGER and implemented in their tools and freely implemented in OpenOCD. It is based on basic memory reads and writes to transfer data bidirectionally between target and host. The specification is independent of the target architecture. Every target that supports so called _"background memory access"_, which means that the target memory can be accessed by the debugger while the target is running, can be used. This interface is the fastest alternative for semihosting. It's speed is determined by the debug probe speed, (this implementation was tested using 12MHz and 24MHz JTAG probe; 6MHz and 4MHz SWD).
This change implements two RTT channels:
1) `console` which is used `in parallel to UART console` (but through debug …
> Implement Real Time Transfer (RTT pipe) device driver

- hal/riscv64/cpu.h
- hal/riscv64/sbi.c
- hal/riscv64/sbi.h
> riscv64: add system reset handling

- hal/armv7a/imx6ull/config.h
- hal/armv7a/zynq7000/config.h
- hal/armv7m/imxrt/10xx/105x/config.h
- hal/armv7m/imxrt/10xx/106x/config.h
- hal/armv7m/imxrt/117x/config.h
- hal/armv7m/stm32/l4/config.h
- hal/armv8m/nrf/91/config.h
- hal/ia32/config.h
- hal/ia32/efi/kernel/cpu.h
- hal/riscv64/generic/config.h
- hal/sparcv8leon3/gaisler/gr712rc/config.h
- hal/sparcv8leon3/gaisler/gr716/config.h
> cleanup headers

- syspage.c
> syspage_entryAdd: fix map size check

- hal/armv7m/imxrt/10xx/105x/imxrt.c
- hal/armv7m/imxrt/10xx/106x/imxrt.c
- hal/armv7m/imxrt/117x/imxrt.c
- Fix invalid offset in `_imxrt_IOpadGetReg`
- MISRA
> hal/armv7m: Fix invalid memory accesses

- hal/armv7m/imxrt/10xx/105x/imxrt.c
- hal/armv7m/imxrt/10xx/106x/imxrt.c
- hal/armv7m/imxrt/117x/imxrt.c
- hal/armv7m/imxrt/hal.c
- hal/armv7m/stm32/hal.c
- hal/armv7m/stm32/l4/stm32l4.c
> !armv7m: Get boot reason, clear status and pass it to the kernel

- hal/armv7m/imxrt/117x/imxrt.c
> imxrt117x: Change ipg_clk_16M source to the 24 MHz OSC

- cmds/Makefile
- cmds/stop.c
- hal/armv7a/imx6ull/Makefile
- hal/armv7a/zynq7000/Makefile
- hal/armv7m/imxrt/10xx/105x/Makefile
- hal/armv7m/imxrt/10xx/106x/Makefile
- hal/armv7m/imxrt/117x/Makefile
- hal/armv7m/stm32/l4/Makefile
- hal/armv8m/nrf/91/Makefile
- hal/ia32/Makefile
- hal/riscv64/generic/Makefile
- hal/sparcv8leon3/gaisler/gr712rc/Makefile
- hal/sparcv8leon3/gaisler/gr716/Makefile
> cmd: Add stop command

- devices/flash-mps3an536/Makefile
- devices/flash-mps3an536/flashdrv.c
- devices/uart-cmsdk-apb/Makefile
- devices/uart-cmsdk-apb/uart.c
- hal/armv8r/Makefile
- hal/armv8r/_cache.S
- hal/armv8r/_exceptions.S
- hal/armv8r/_interrupts.S
- hal/armv8r/cache.h
- hal/armv8r/cpu.c
- hal/armv8r/cpu.h
- hal/armv8r/exceptions.c
- hal/armv8r/mps3an536/Makefile
- hal/armv8r/mps3an536/_init.S
- hal/armv8r/mps3an536/config.h
- hal/armv8r/mps3an536/console.c
- hal/armv8r/mps3an536/hal.c
- hal/armv8r/mps3an536/interrupts.c
- hal/armv8r/mps3an536/timer.c
- hal/armv8r/string.c
- hal/armv8r/types.h
- ld/armv8r52-mps3an536.ldt
> add support for ARMv8 Cortex-R52 (MPS3 AN536) platform

- ld/armv8r52-mps3an536.ldt
> ld/armv8r52: update SIZE_PAGE definition

- devices/uart-grlib/uart.c
- hal/riscv64/noelv/noelv.h
- hal/sparcv8leon3/gaisler/console.c
- hal/sparcv8leon3/gaisler/gr712rc/gr712rc.c
- hal/sparcv8leon3/gaisler/gr712rc/peripherals.h
- hal/sparcv8leon3/gaisler/gr716/peripherals.h
- hal/sparcv8leon3/gaisler/timer.c
JIRA: RTOS-885
Cleanup before GR740 port
> Cleanup sparcv8leon3 port

- hal/sparcv8leon3/_interrupts.S
- hal/sparcv8leon3/gaisler/Makefile
- hal/sparcv8leon3/gaisler/generic/Makefile
- hal/sparcv8leon3/gaisler/generic/_init.S
- hal/sparcv8leon3/gaisler/generic/config.h
- hal/sparcv8leon3/gaisler/generic/generic.c
- hal/sparcv8leon3/gaisler/generic/generic.h
- hal/sparcv8leon3/gaisler/generic/hal.c
- hal/sparcv8leon3/gaisler/generic/peripherals.h
- hal/sparcv8leon3/gaisler/timer.c
- ld/sparcv8leon3-generic.ldt
> add sparcv8leon3-generic target

- devices/flash-imxrt/nor/nor.c
> flash-imxrt: Support W25Q512NW-IQ/IN flash chips

- phfs/phfs.c
In complex projects we may have multiple user scripts (FW banking) and applications / blobs. For now increase the max size (RAM in PLO is not a problem).
JIRA: NIL-550
> phfs: increase max aliases size to 32

- hal/ia32/console-vga.c
> hal/ia32: adapt to changed hal_in functions

- Makefile
- riscv-sbi/Makefile
JIRA: CI-494
Needed especially for SBI as it was not rebuilt on payload change.
> make: fix incremental build

- cmds/Makefile
- cmds/vbe.c
- hal/ia32/Makefile
- hal/ia32/config.h
- hal/ia32/memory.c
- ld/ia32-generic.ldt
- syspage.c
- syspage.h
Adds command `vbe` for setting up graphics mode using VESA VBE 2.0 real mode interface. The command checks whether a specified mode (preferred/fallback) is supported by the VGA controller, fetches its details, sets it and stores necessary info (width, height, bpp, framebuffer address, etc.) in the syspage. The info can be then queried using platformctl by userspace apps
JIRA: RTOS-906
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1176
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/596
> cmd: add vbe modesetting command

- hal/armv8r/mps3an536/Makefile
> hal/armv8r: Disable fpu in compile options

- hal/sparcv8leon/gaisler/timer.c
JIRA: RTOS-969
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1228
> hal/sparcv8leon: change timer irq defines

- cmds/Makefile
- cmds/watchdog.c
- hal/armv7m/imxrt/10xx/105x/imxrt.c
- hal/armv7m/imxrt/10xx/105x/imxrt.h
- hal/armv7m/imxrt/10xx/106x/imxrt.c
- hal/armv7m/imxrt/10xx/106x/imxrt.h
- hal/armv7m/imxrt/117x/Makefile
- hal/armv7m/imxrt/117x/imxrt.c
- hal/armv7m/imxrt/117x/imxrt.h
- hal/armv7m/imxrt/117x/peripherals.h
- hal/armv7m/imxrt/hal.c
Introduces `WATCHDOG_PLO` and `WATCHDOG_PLO_TIMEOUT_MS` defines, which may
be used separately:
- `WATCHDOG_PLO` - enables the watchdog (with a default timeout of 128s
if `WATCHDOG_PLO_TIMEOUT_MS` was not provided);
- `WATCHDOG_PLO_TIMEOUT_MS` - reconfigures the timeout. If the watchdog
is disabled (as reported by hardware), then it is NOT enabled
(`WATCHDOG_PLO` must be truthy if plo is supposed to enable the
watchdog itself).
Auto-reload is implemented using watchdog's timer interrupt and can be
used whenever some tasks in plo will take a long time to run.
Warning: this interrupt cannot be disabled once enabled, so it is
masked when leaving plo.
WDOG3 and WDOG4 are properly disabled but can be reconfigured later.
`watchdog` command is added.
> imxrt117x: Use WDOG1 and support auto-reload

- cmds/ptable.c
- lib/ptable.c
- lib/ptable.h
> lib/ptable: Refactor partition type handling and info

- hal/armv7m/imxrt/10xx/105x/imxrt.c
- hal/armv7m/imxrt/10xx/106x/imxrt.c
- hal/armv7m/imxrt/117x/imxrt.c
> hal/imxrt: update boot reason to include all reset flags

- cmds/console.c
- hal/ia32/Makefile
- hal/ia32/console-serial.c
- hal/ia32/console-vga.c
- hal/ia32/console.c
- hal/ia32/console.h
- lib/console.c
- lib/console.h
> console: support mirroring to another device

- hal/armv8m/mcx/n94x/n94x.c
> hal/mcxn94x: Enable Mailbox

- devices/uart-zynq/uart.c
- hal/armv7m/imxrt/10xx/105x/peripherals.h
There are some useful warning flags, which are enabled in internal projects, like `-Wundef` and `-Wshadow`.
This commit allow plo to be build with `-Wundef` without warnings
To enable `-Wundef` flag in the future
> Fixes to allow enabling -Wundef

- hal/aarch64/string.c
- hal/armv7a/string.c
- hal/armv7m/string.c
- hal/armv7r/string.c
- hal/armv8m/string.c
- hal/armv8r/string.c
- hal/ia32/string.c
- hal/riscv64/exceptions.c
- hal/riscv64/noelv/Makefile
- hal/riscv64/noelv/noelv.c
- hal/riscv64/string.c
- hal/sparcv8leon/string.c
- hal/string.h
- riscv-sbi/core/_interrupts.S
- riscv-sbi/core/exceptions.c
- riscv-sbi/platform/noelv/platform.c
> riscv64 fixes for latest GRLIB build

- hal/aarch64/zynqmp/types.h
- hal/armv7a/imx6ull/types.h
- hal/armv7a/zynq7000/types.h
- hal/armv7m/imxrt/types.h
- hal/armv7m/stm32/types.h
- hal/armv7r/types.h
- hal/armv8m/mcx/types.h
- hal/armv8m/nrf/types.h
- hal/armv8m/stm32/types.h
- hal/armv8r/types.h
- hal/ia32/efi/kernel/cpu.h
- hal/ia32/types.h
- hal/riscv64/types.h
- hal/sparcv8leon/gaisler/types.h
- riscv-sbi/include/types.h
JIRA: RTOS-620
fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1261
fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1238
> !hal: make time_t signed

- cmds/stop.c
- cmds/wait.c
- cmds/watchdog.c
> Add missing const
