ia32/Makefile

Adding auto-detection of BCC/NCC compilers and throwing error if none exists.

ia32 Makefile fix

---

ia32/Makefile

There is a wrong indent in if clause in ia32 Makefile which causes build to break.

ia32: fix indentation error

---

armv7m7-imxrt106x/phfs.c

For `pdn == PDN_NB` array index is out of range.
I also changed the indentation from spaces to tabs.
**1.** 
instead
```
if (pdn >= PDN_NB)
return ERR_ARG;
return phfs_handlers[pdn].open(phfs_handlers[pdn].dn, name, flags);
```
better will be
```
if (pdn < sizeof(phfs_handlers) / sizeof(phfs_handlers[0]))
return phfs_handlers[pdn].open(phfs_handlers[pdn].dn, name, flags);
return ERR_ARG;
```
**2.** 
instead
```
void phfs_init(void)
{
int i;
/* Handlers for flash memories */
for (i = 0; i < 2; ++i) {
phfs_handlers[PDN_FLASH0 + i].open = flash_open;
phfs_handlers[PDN_FLASH0 + i].read = flash_read;
phfs_handlers[PDN_FLASH0 + i].write = flash_write;
phfs_handlers[PDN_FLASH0 + i].close = flash_close;
phfs_handlers[PDN_FLASH0 + i].dn = i;
}
phfs_handlers[PDN_COM1].open = phoenixd_open; …
```

phfs.c: fixed array index check

---

armv7m7-imxrt106x/low.c

Change of register usage in inline assembly.
Code disassembly:
- **current version**
```
00000000 <low_memcpy>:
0:   b470            push    {r4, r5, r6}
2:   460d            mov     r5, r1
4:   4616            mov     r6, r2
6:   4631            mov     r1, r6
8:   462b            mov     r3, r5
a:   4604            mov     r4, r0
c:   ea43 0204       orr.w   r2, r3, r4
10:   f012 0203       ands.w  r2, r2, #3
14:   d108            bne.n   28 <low_memcpy+0x28>
16:   2904            cmp     r1, #4
18:   bf22            ittt    cs
1a:   f853 2b04       ldrcs.w r2, [r3], #4
1e:   f844 2b04       strcs.w r2, [r4], #4
22:   f1b1 0104       subscs.w        r1, r1, #4
26:   d2f6            bcs.n   16 <low_memcpy+0x16>
28:   2900            cmp     r1, #0
2a:   bf1e            ittt    ne
2c: …
```

low.c: optimization low_memcpy()

---

script.c
script.h

This change makes a distinction between the maximum number of commands and script lines, increases this limit and warns when the maximum number of script lines is exceeded.
This pull request relates to issue https://github.com/phoenix-rtos/plo/issues/21

script: distinction between max commands and script lines count

---

armv7m7-imxrt106x/low.c
armv7m7-imxrt106x/serial.c
plostd.c

The plo uses two uarts: 
- uart1: the console
- uart3: for communication with phoenixd.
When using the uart3 with different settings than those set by the plo, I've observed spontaneous freezing of the uart3 in Phoenix-RTOS (imxrt-multi and libtty), after changing the baud rate from that set by plo (115200) to a different speeds (9600, 230400, 460800) and setting raw mode.
The TX fifo of uart3 seemed not to be flushed before a jump to the system. I've added a cleanup routine and a sleep time of ~100ms additionally, because a quick reset of (uart1), which is used by the console, leads to the loss of the last messages from plo before jump to the system.

imxrt106x: fix spontaneous freezes of the uart

---

armv7m7-imxrt117x/Makefile
armv7m7-imxrt117x/cmd.c
armv7m7-imxrt117x/imxrt.c
armv7m7-imxrt117x/low.c
armv7m7-imxrt117x/serial.c

Fixed array index chaecking:
```
low_irqinst()
serial_read()
serial_write()
``` 
These bugs are also in imxrt106x.
Additionally:
- `_imxrt_systickSet()`: compiler warnings have been eliminated
- removed whitespaces.

imxrt117x: fixed array index checking

---

armv7m7-imxrt106x/imxrt.c

This commit is analogous to https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/178 because of the same procedure.
* The debugger functionality has been checked against to use J-Link (jtag / swd) and [pyOCD](https://github.com/pyocd/pyOCD) (using CMSIS-DAP available on the mimixrt1064-evk board).
* Also a minor update in the comment about clock freq.

Enable jtag/debugger and some fixes

---

ia32/Makefile

Change is supposed to make possible building plo in serial mode by setting variable explicitly:
TARGET=ia32-generic CONSOLE=serial phoenix-rtos-build/build.sh ...
Referenced by:
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/175
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/46

Support serial console by parameter

---

cmd.c

I have two comments:
1. instead of going throught loop
```
if (src->datasz == 0 && src->datasz == 0) {
size = 0;
}
```
give e.g. this
```
if (src->datasz == 0 && src->datasz == 0) {
return 0;
}
```
2. after
```
if ((res = phfs_read(src->dn, src->handle, &src->dataOffs, buff, chunk)) < 0) {
plostd_printf(ATTR_ERROR, "\nCan't read segment data\n");
return ERR_PHFS_FILE;
}
```
add
```
if ((res == 0) { // end of file
break;
}
```

cmd.c: corrected condition

---

armv7m7-imxrt106x/peripherals.h

The flag UART_CONSOLE_PLO is optional. Should be
used when it is necessary to split up system console
with one for plo. If flag is not defined UART_CONSOLE
takes effect.

imxrt: add separate uart console flag for plo

---

armv7a9-zynq7000/syspage.c
armv7m7-imxrt106x/syspage.c
armv7m7-imxrt117x/syspage.c
cmd.c

This change fixes parsing of arguments passed to syspage and error checking in plo app command. Prior to this change arguments were truncated e.g `app flash0 @lwip;pppou:/dev/uart3:460800:up xip1 ocram2` was resolved as process name `lwip` with argv[1]= `pppou:/dev/` but expected was argv[1]=`pppou:/dev/uart3:460800:up`.
Working examples based on correct syntax:
```
app flash0 @lwip;pppou:/dev/uart3:460800:up xip1
app flash0 @ps_g3_mac_srv;msg=/dev/sap1;band=cen_a;run=3 xip1 ocram2
```
and downloading app to internal ram through auxiliary uart (using phoenixd):
```
app com1 g3adp_test;log7;m=/dev/sap1;testcase=2:8:0:18
```
JIRA: RTOS-4 , RTOS-5

armv7m7: Fix syspage arguments parsing

---

armv7a9-zynq7000/syspage.c
armv7m7-imxrt106x/syspage.c
armv7m7-imxrt117x/syspage.c
cmd.c
syspage.h

This change adds the ability to choose whether the `app` specified in the `plo` script or on the command line is to be started (`-x` flag) by the kernel at startup or not.
Usage examples, applications that will be started by the kernel:
```
(plo)% app flash0 -x @dummyfs xip1 dtcm
(plo)% app flash0 -x @imxrt-multi xip1 dtcm
(plo)% app flash0 -x @psh xip1
(plo)% app flash0 -x @mserver;cfg=/dev/xmsg xip1 ocram2
```
Apps that will not be started by the kernel:
```
(plo)% app flash0 @app1 xip1
(plo)% app flash0 @app2
```
Those applications (`app1`, `app2`) may be later started with `psh` command `sysexec`:
```
(psh)% sysexec ocram2 app1
(psh)% sysexec ocram2 app2 arg1 arg2 arg3
```

armv7m7: Add `app` command executable flag `-x`

---

cmd.c
ia32/cmd.c

Majority of cmd.c based on ia32/cmd.c
So that this issue has to be fixed in ia32 as well.

cmd: fix checking elf's header identification

---

Makefile
hal/armv7a/zynq7000/Makefile
hal/armv7a/zynq7000/config.h
hal/armv7m/imxrt106x/Makefile
hal/armv7m/imxrt106x/config.h
hal/armv7m/imxrt117x/Makefile
hal/armv7m/imxrt117x/config.h
plostd.c
syspage.c
syspage.h

The following PR contains:
1. Making one instance of generic syspage in phoenix-rtos-loader.
2. Adding architecture dependent field (**syspage_arch_t**).
3. Changing types of fields: size description **u32 -> size_t** and address description **void * -> addr_t**
4. Removing long references to nested structure elements which cause less code readability. 
@pawelpisarczyk, I would like to ask you to check whether current syspage structure is consistent with our assumptions, I think that the most important for You are mentioned points 2 and 3.
If changes in **syspage_t** structure are approved, I will change the **syspage_t** structure in phoenix-rtos-kernel to make it consistent with a loader.

generic syspage

---

Makefile
_startc.c
devices/devs.c
devices/devs.h
hal.h
hal/armv7a/zynq7000/Makefile
hal/armv7a/zynq7000/_startup.S
hal/armv7a/zynq7000/config.h
hal/armv7a/zynq7000/hal.c
hal/armv7m/imxrt106x/Makefile
hal/armv7m/imxrt106x/_startup.S
hal/armv7m/imxrt106x/config.h
hal/armv7m/imxrt106x/hal.c
hal/armv7m/imxrt117x/Makefile
hal/armv7m/imxrt117x/_startup.S
hal/armv7m/imxrt117x/config.h
hal/armv7m/imxrt117x/hal.c

Due to the fact that [PR](https://github.com/phoenix-rtos/plo/pull/51) has been growing, it is separated into different PRs which will be merged into a `feature/devs` branch in plo. When the whole functionality will done, the `feature/devs` will be merged into master.
This PR provides the following changes:
- add `_startc.c` to handle constructors and destructors
- add device interface to allow initialize specific driver based on platform settings
For example, registration of uart driver:
```
int uart_init(int dn, dev_handler_t *h)
{
...
}
__attribute__((constructor)) static void uart_regDev(void)
{
devs_regDriver(DEV_UART_ID, uart_init);
}
```
If this mechanism is accepted I will implement it in the current drivers and will add changes it into this PR.

plo: constructors, destructors and device module

---

hal/armv7m/imxrt117x/imxrt.c

JIRA: NIL-123
This should do for initializing all pins as slow and weak for EMC purpose. If someone need pin to be fast, they should reconfigure pin as they wish.
Not tested on HW yet, don't merge without verification. Might have bad effect on FlexSPI

imxrt117x: Init all pads as slow slew-rate and low drive strength (EMC)

---

cmds/alias.c
cmds/console.c
cmds/copy.c
cmds/dump.c
cmds/map.c
cmds/phfs.c
cmds/syspage.c
cmds/wait.c

Instead of `strlen()` just check the value of `*end`.

cmds: simpler number validation

---

cmds/map.c

- corrected argument count check
- changed two `hal_strlen()` calls to one
- `argID` is redundant, number of arguments is fixed

cmds/map: simplification of the code

---

cmds/call.c

- unnecessary `hal_memset()` has been removed
- buffer length check has been corrected
- added support for case when the script does not end with `\n`

cmds/call: simplification of the code

---

hal/armv7a/zynq7000/zynq.c

zynq7000: if code runs under qemu, ddr initialization should be skipped

---

cmds/cmd.c
cmds/cmd.h

Line:
```
if (cmd_getnext(line, &p, "\n", DEFAULT_CITES, word, sizeof(word)) == NULL) {
```
allows cmdline as multiline
Line:
```
if (cmd_getnext(word, &wp, DEFAULT_BLANKS, DEFAULT_CITES, cmd, sizeof(cmd)) == NULL) {
```
allows spaces in the command

cmds/cmd: the use of cites has been changed

---

devices/uart-imxrt106x/uart.c
devices/uart-imxrt117x/uart.c
devices/uart-zynq7000/uart.c
hal/armv7a/zynq7000/timer.c
hal/armv7m/imxrt106x/_startup.S
hal/armv7m/imxrt106x/timer.c
hal/armv7m/imxrt117x/timer.c
hal/timer.h

This PR should solve the problem with UART driver which causes that plo occasionally freezes on imxrt106x.
Within this changes the volatile types are added to variables which values are changed in interrupts.
@jsarzy, please test this solution with runner.

plo: fix uart

---

cmds/app.c
phfs/phfs.c

Quick fixes about issues reported in Jira: RTOS-41, RTOS-42
Previously max. allowed app name length was up to 15 characters + 1 null byte (16 bytes), after change #71 it is 14 characters + 1 null byte (15 bytes). Syspage actually do accept 15 characters + 1 null byte (16 bytes), take a look [plo/syspage.c#L53](https://github.com/phoenix-rtos/plo/blob/9afdfa3892030629ee89630a4299e7fbea30e38e/syspage.c#L53) and [plo/syspage.c#L629](https://github.com/phoenix-rtos/plo/blob/9afdfa3892030629ee89630a4299e7fbea30e38e/syspage.c#L629)
One of the projects require more programs to be later executed with `sysexec`, limit of 10 is too low.

Quick fixes of max allowed files in phfs and the length of an app

---

cmds/app.c
cmds/go.c
cmds/kernel.c
cmds/map.c
cmds/syspage.c
hal/armv7a/zynq7000/hal.c
hal/armv7m/imxrt106x/hal.c
hal/armv7m/imxrt117x/hal.c
hal/hal.h
syspage.c
syspage.h

Two improvements within this pull request:
- add the ability to indicate an alias name to the `kernel` command like e.g. `kernel flash1 my-kernel` instead of hard-coded name `phoenix-armv7m7-imxrt106x.elf`.
- add kernel address validation in the `go` command if the kernel was properly loaded
- and a few minor fixes
JIRA: RTOS-43, RTOS-44, PD-89, PD-117

cmd/kernel: add optional kernel alias/name argument

---

devices/flash-imxrt/romapi-imxrt106x.c
devices/flash-imxrt/romapi-imxrt117x.c
hal/armv7m/imxrt/10xx/_startup.S
hal/armv7m/imxrt/10xx/hal.c
hal/armv7m/imxrt/117x/_startup.S

- change interrupts priority for imxrt106x,
- fix interrupt dispatch for imxrt,
- disable interrupts while ROM API is used.
JIRA: PD-123
When `copy` command form usb0 to flash1 is proceeded by many `app usb0` command, the exception is called. This behavior only occurs during access to internal flash.
At the same time there are interrupts from usb, timer and uart.
The same problem was described on NXP forum:
https://community.nxp.com/t5/i-MX-RT/Programming-the-internal-Flash-of-RT1064/m-p/883989

plo: fix interrupts and disable interrupts when ROM API is used

---

cmds/script.c

Command `script` without any arguments shows preinit script. Otherwise, the device, script's name and magic number is needed.
Unification of commands.

cmd/script: usage without arguments shows preinit script

---

hal/armv7m/imxrt/10xx/imxrt.c
hal/armv7m/imxrt/117x/imxrt.c

JIRA: PD-131
While interrupt is cleared, it shouldn't be done using logical OR operation. It causes that several other interrupts might be cleared as well.
https://developer.arm.com/documentation/dui0646/c/cortex-m7-peripherals/nested-vectored-interrupt-controller/interrupt-clear-enable-registers?lang=en

hal/armv7m: fix setting interrupts

---

cmds/go.c
devices/uart-imxrt106x/uart.c
devices/uart-imxrt117x/uart.c
devices/uart-zynq7000/uart.c
hal/armv7a/zynq7000/hal.c
hal/armv7m/imxrt/10xx/hal.c
hal/armv7m/imxrt/117x/hal.c

Invoke `dev_done()` before jump to phoenix-rtos-kernel.
JIRA: PD-137
Interrupts from devices should be disabled before jumping to kernel.

devices: clean up devices before jump to kernel

---

Makefile

JIRA: PD-138
Preinit script for plo located in ram cannot call user script.

Makefile: image located in ram should have different preinit script

---

cmds/cmd.c
lib/console.c
lib/console.h
phfs/msg.c

Changed command prompt character read timeout to infinite value.
Fixed missing interface changes from [ Clean up standard functions interface #106 ](https://github.com/phoenix-rtos/plo/pull/106)
Cleaner code + there is additional benefit of blocking character read when using tty-bios on ia32-generic target (no busy waiting for character).
[JIRA: PD-152](https://jira.phoenix-rtos.com/browse/PD-152)

cmds/cmd.c: changed reading command prompt character timeout to infinite

---

Makefile

The ram image isn't necessary on ia32-generic target - added rule for building base image only (`make base`).
[JIRA: PD-154](https://jira.phoenix-rtos.com/browse/PD-154)

add makefile rule for building base image only

---

syspage.c

Disabled top relative map address validation.
In syspage_validateKernel() we check if `kernel.text` and `kernel_entry` are below their map top address (I believe they don't have to be). I'm not sure why we have this check so I disabled it for now. The change is required for kernel jump to work on new plo for ia32-generic.
[JIRA: PD-97](https://jira.phoenix-rtos.com/browse/PD-97)

syspage.c: disable top validation in syspage_validateAddrMap()

---

devices/tty-bios/tty-bios.c
hal/ia32/console-vga.c
hal/ia32/hal.c

Replaced BIOS int 0x10 usage with direct VGA memory access.
The console felt sluggish.
[JIRA: PD-169](https://jira.phoenix-rtos.com/browse/PD-169)

tty-bios/console-vga: replace BIOS int 0x10 console with direct VGA memory access

---

devices/tty-bios/tty-bios.c
hal/ia32/console-vga.c

Bug fix to changes introduced in the previous commit + renamed variable.
The `\b` key doesn't move cursor to the previous row.
[JIRA: PD-169](https://jira.phoenix-rtos.com/browse/PD-169)

tty-bios/console-vga: fix \b moving cursor to the previous row + rename 'curs' variable to 'pos'

---

cmds/script.c

This PR fixes an index outside the range of the array.
Array `buff` is defined as:
```
char buff[SIZE_CMD_ARG_LINE];
```
in loop
```
do {
if ((res = phfs_read(h, offs, (u8 *)buff, SIZE_CMD_ARG_LINE)) < 0) {
log_error("\nCan't read %s from %s", argv[2], argv[1]);
return res;
}
buff[res] = '\0';
lib_printf(buff);
offs += res;
} while (res > 0);
```
if `res == SIZE_CMD_ARG`
`buff[res] = '\0'` is out of range.
Alternatively, define the array as:
```
char buff[SIZE_CMD_ARG_LINE + 1];
```

cmds/script: array index out of range has been fixed

---

devices/usbc-cdc/usbphy-imxrt106x.c
devices/usbc-cdc/usbphy-imxrt117x.c
devices/usbc-cdc/usbphy-zynq7000.c
hal/armv7m/imxrt/117x/Makefile
hal/armv7m/imxrt/117x/imxrt.c
hal/armv7m/imxrt/117x/imxrt.h
hal/armv7m/imxrt/117x/peripherals.h

I'm adding an OTG1 USB device phy layer to the `imxrt1176` platform. Additionally PHY initialization requires LPCG115 gate to be enabled, that's why I'm adding `_imxrt_setDirectLPCG()` function with set of appropriate `enum's` .
JIRA: NIL-141

imxrt/117x: add usb physical layer

---

devices/flash-zynq7000/flashcfg.c
devices/flash-zynq7000/flashdrv.c
devices/flash-zynq7000/qspi.c

- handle flash memory available on qemu,
- clean up qspi liner mode,
- fix read operation.

flash-zynq7000: handle flash memory available on qemu

---

hal/armv7m/imxrt/10xx/console.c
hal/armv7m/imxrt/117x/console.c

JIRA: RTOS-118
On `imxrt117x` the `UART_CONSOLE_PLO`, and `UART_CONSOLE` environment variables do not configure the (so-called) early plo console (default port is hardcoded) side effect of this may observed when plo starts:
Hardcoded values are assigned to `UART1` which is not the default console port for the current project being developed on `imxrt117x`, for ease of use with `BOARD_CONFIG`,  `UART_CONSOLE` or `UART_CONSOLE_PLO` may be used to assign a default port per project. I assume the macros provided are per each `console.c`, but may be moved to `peripherals.h`.
This commit fixes that, so with default `UART_CONSOLE` from `peripherals.h` which is `UART11` it looks like:

imxrt: use UART_CONSOLE to setup early console

---

devices/flash-imxrt/flashcfg.c
devices/flash-imxrt/flashcfg.h

This PR adds support for quad spi flash IS25xx128 used in MIMXRT1170-EVK evaluation board. Additionally fixes the redundant use of the write command in the flexspi lookup table for the chip erase entry.

add support for quad spi flash memory on MIMXRT1170-EVK evaluation board

---

devices/uart-stm32l4x6/uart.c

uart-stm32l4: Wait for transmission complete during sync

---

hal/armv7m/stm32/l4/console.c

JIRA: SKAL-455
There was a problem during uart reconfiguration (basic console -> plo uart driver) of interrupting ongoing transmission

stm32l4: Fixed not waiting for transmission complete on console TX

---

hal/armv7a/imx6ull/hal.c
hal/armv7a/zynq7000/hal.c
hal/armv7m/imxrt/hal.c
hal/armv7m/stm32/hal.c

The porosed fix reduces the size of generated code about 400 bytes.
Results for targets:
```
now   new   diff
plo-armv7a7-imx6ull.img   41204 40812 392
plo-armv7a9-zynq7000.img  46860 46452 408
plo-armv7m4-stm32l4x6.img 34772 34356 416
plo-armv7m7-imxrt106x.img 53456 53036 420
plo-armv7m7-imxrt117x.img 50668 50248 420
```
The `hal_memoryGetNextEntry()` and `hal_getMinOverlappedRange()` functions use only three members of the `mapent_t` structure: `start, end, type`.
I have abandoned the use of the `hal_memset()` and `hal_memcpy()` functions.
As a result, the compiler uses only registers to store local variables (without using the stack).
The result is shown above.

arm/hal.c: reduce code size hal_memoryGetNextEntry()

---

hal/armv7m/stm32/l4/stm32l4.c

stm32l4: Fix bad SCB FPU control registers offset

---

devices/flash-zynq7000/flashcfg.c
devices/flash-zynq7000/flashcfg.h
devices/flash-zynq7000/flashdrv.c

In current implementation the dual and quad mode does not work correctly for 4 byte addressing mode.
For this reason, the read and page program operations are done on single line.
It should be fixed in the future.
PP-278

flash-zynq7000: add operations on 4 byte addresses

---

ld/armv7m4-stm32l4x6.ldt

JIRA: RTOS-233
On STM32L49x/L4Ax devices, the SRAM size should be 320 K (256K + 64K), instead of the  mistakenly set 384 K (256K + 128K).

stm32l4: Fix bad size of the SRAM area map

---

hal/ia32/memory.c

JIRA: RTOS-241
On `ia32`, the `plo image` during the bootstrap process is fully loaded from the hard drive into the RAM, it literally takes an area from `_start` to `_end`  (all sections). It resides there temporarily for the time of the operating system is being loaded. During that time it is required to protect the `.init`, `.text` and `.ro/.data` sections from accidental overwriting by adding a temporary mapping (released after the plo is finished). For example, an accidental overwrite can happen when loading a syspage application into the lower RAM using the plo `app` command, this ends up very bad in the picture below:
Clue:
This happened during loading an application into the "free" (not marked as used by plo image) area which spans form `0x7000` up to `0x172f0` and crashed the plo …

ia32: Add the `plo image` to temporary map

---

hal/armv7m/stm32/hal.c
ld/common/plo-arm.lds
ld/common/plo-ia32.lds

After the modification (stm32l4) so that the plo is loaded into RAM, the `.init`, `.text`, `.rodata` sections were not mapped (map entries), which resulted in considering this area as unallocated. While loading applications to RAM below the first RAM map-entry resulted in overwriting the `plo` image when `plo` is running from the RAM.
The `ia32` scripts have been updated in a similar way to `stm32` to be consistent.

Add plo image to map entries and provide section start/end symbols.

---

Makefile

Makes plo compilable again when scripts are missing.
JIRA: CI-147

make: fix `PLO_SCRIPT_DIR` existence

---

cmds/reboot.c
devices/flash-flexspi/fspi/fspi.c
devices/uart-16550/uart-16550.c
devices/uart-imx6ull/uart.c
devices/uart-imxrt106x/uart.c
devices/uart-imxrt117x/uart.c
devices/uart-stm32l4x6/uart.c
devices/uart-zynq7000/uart.c
hal/armv7a/cpu.c
hal/armv7a/exceptions.c
hal/armv7a/imx6ull/hal.c
hal/armv7a/imx6ull/interrupts.c
hal/armv7a/imx6ull/timer.c
hal/armv7a/zynq7000/hal.c
hal/armv7a/zynq7000/interrupts.c
hal/armv7a/zynq7000/timer.c
hal/armv7m/imxrt/10xx/timer.c
hal/armv7m/imxrt/117x/timer.c
hal/armv7m/imxrt/hal.c
hal/armv7m/interrupts.c
hal/armv7m/stm32/hal.c
hal/armv7m/stm32/l4/timer.c
hal/hal.h
hal/ia32/cpu.c
hal/ia32/exceptions.c
hal/ia32/interrupts.c

New hal API:
- `hal_interruptsEnable` -> `hal_interruptsEnableAll`
- `hal_interruptsDisable` -> `hal_interruptsDisableAll`
- `hal_interruptsEnable(unsigned int irqn)`
- `hal_interruptsDisable(unsigned int irqn)`
Changes are applied to all architectures and device drivers.
Device drivers disabled all interrupts which is not an optimal method of synchronization. In the new approach, the device disable only specific interrupt.

Allow to enable/disable specific interrupt in IRQ controller

---

cmds/dump.c

Arguments cannot be empty strings, so checking if they are empty is unnecessary.
I added a check if the variable`length` is different from zero.

cmds/dump.c: remove unnecessary conditions

---

hal/armv7a/imx6ull/types.h
hal/armv7a/zynq7000/types.h
hal/armv7m/imxrt/types.h
hal/armv7m/stm32/types.h
hal/ia32/types.h
lib/list.c

`NULL pointer constant` of the form `(void *)0` is permitted, whether or not it was expanded from `NULL`. The use of `0` implies `integer constant`, not a `pointer constant`. Using `NULL` rather than `0` makes it clear that a `null pointer constant` was intended.
JIRA: RTOS-282

Conform NULL pointer macro with MISRA rule 11.9

---

devices/flash-flexspi/nor/nor.c
ld/armv7m7-imxrt117x.ldt

All code between `flexspi_xferExec` and transfer finish (successful return from nor_waitBusy) needs to be runnable without prefetch.
Move all relevant functions to RAM.
JIRA: BES-239

flash-flexspi: move nor_* functions to RAM

---

cmds/Makefile
cmds/cmd.c
cmds/cmd.h
cmds/otp.c
hal/armv7a/string.c
hal/armv7m/imxrt/10xx/Makefile
hal/armv7m/imxrt/10xx/otp.c
hal/armv7m/imxrt/117x/Makefile
hal/armv7m/imxrt/117x/otp.c
hal/armv7m/imxrt/hal.c
hal/armv7m/imxrt/otp.h
hal/armv7m/string.c
hal/armv8m/string.c
hal/ia32/string.c
hal/string.h
lib/Makefile
lib/getopt.c
lib/getopt.h
lib/lib.h

This change adds the `otp` command for reading and writing the `OCOTP` memory/registers on  the i.MX RT 117x and 10xx family.
And additionally introduces `lib_getopt()`, this functionality will simplify the portability of commands, as well as simplify parsing of commands (which is currently performed by each command on its own and increase the plo code size), using common parser will also potentially reduce the plo size (on a `DRY principle`) if all commands will be updated to use the `well known` common argument parser.
JIRA: NIL-374

imxrt: Add otp command with lib_getopt

---

cmds/copy.c
devices/usbc-cdc/cdc.c
devices/usbc-cdc/client.c
devices/usbc-cdc/client.h
devices/usbc-cdc/ctrl.c
devices/usbc-cdc/desc.c
devices/usbc-cdc/usb.h

This change fixes, adds:
* the ability to respond to disconnection and re/connection of the USB cable
* response to faults in the result of a broken USB connection (faulty cable),
* timeout check for stalled endpoints,
* errno like results,
* fixes allocations and improves memory access (unexpected hang-ups during bad qtd access and usb enumeration (in the third, fourth turn after cable reconection),
* resolves issues with hangups and restarts after the third-fourth`copy usb0 ..` command (bus fault exception),
* adjusts the style to be more MISRA compliant.
JIRA: RTOS-324
https://github.com/phoenix-rtos/phoenix-rtos-project/issues/489
https://github.com/phoenix-rtos/phoenix-rtos-project/issues/488

usb-cdc: Fix usb device dis/connect state

---

phfs/msg.c
phfs/msg.h
phfs/phoenixd.c

Add explicit serialization and deserialization of structs in `phoenixd` and `msg`.
- Required for big endian support
- JIRA: RTOS-351

msg: add serialization and deserialization functions

---

cmds/copy.c

JIRA: RTOS-375
Fixed parsing of arguments in copy.
If offset and size was provided to copy the options would parse properly.

copy: fix arg parsing

---

hal/armv7a/imx6ull/_init.S

JIRA: RTOS-398
imx6ull: boot from qspi nor flash
imx6ull lacks support for starting from flash
- [] This PR needs additional PRs to work (list the PRs, preferably in merge-order).

imx6ull: boot from qspi nor flash

---

hal/armv7m/imxrt/10xx/console.c
hal/armv7m/imxrt/10xx/peripherals.h
hal/armv7m/imxrt/117x/console.c
hal/armv7m/imxrt/117x/peripherals.h

`UART1` is the default console port for imxrt1176-evk to which FreeLink virtual comm. port (USB ACM-CDC interface) is connected. This setting may be overridden in board config by `UART_CONSOLE` define or if plo console should use dedicated uart in such case `UART_CONSOLE_PLO` in board config may be used.
JIRA: NIL-422

imxrt117x: Use default uart setup for imxrt1176-evk

---

hal/armv7m/Makefile
hal/armv7m/exceptions.c
hal/armv7m/imxrt/10xx/_init.S
hal/armv7m/imxrt/117x/_init.S
hal/armv7m/stm32/l4/_init.S
ld/armv7m7-imxrt117x.ldt

This change adds exception handler (on imxrt and stm32l4 targets) which dumps CPU context when exception occurs.
JIRA: RTOS-368

Add  exception handler on `armv7m`

---

hal/armv7a/imx6ull/Makefile

nand-imx6ull: add missing define in Makefile

---

hal/armv7a/string.c
hal/armv7m/string.c
hal/armv8m/string.c
hal/ia32/string.c
hal/sparcv8leon3/string.c

JIRA: RTOS-475
Changes return value in hal_memcpy to original destination.
Fixes comment: https://github.com/phoenix-rtos/plo/pull/219#issuecomment-1554090667
JIRA: RTOS-475

hal/string: correct `hal_memcpy` return value

---

cmds/bootcm4.c

Fix for overwriting locally stored vector table address before checking if it is out of bounds.
JIRA: RTOS-457

cmds/bootcm4: Fix address overwrite before check

---

devices/flash-zynq7000/flashcfg.h
devices/flash-zynq7000/flashdrv.c

JIRA: RTOS-482
When trying to erase to the end of the device driver was doing wrong region checks.

flash-zynq7000: fix erase on last block

---

hal/sparcv8leon3/Makefile

Kernel has support for register windows, `-mflat` flag no longer used.
JIRA: RTOS-406

Leon3: Remove `-mflat` flag filter from makefile

---

devices/flash-imx6ull/qspi/qspi.c
hal/armv7a/imx6ull/_init.S

JIRA: RTOS-496
The clocks were too fast and on same examples this resulted in data corruption while loading the image by bootrom.

imx6ull: slow down qspi clocks

---

hal/sparcv8leon3/_init.S
hal/sparcv8leon3/_traps.S
hal/sparcv8leon3/gr716/gr716.c
ld/sparcv8leon3-gr716.ldt

GR716: Implement plo copy to SRAM

---

hal/armv7a/exceptions.c
hal/armv7a/imx6ull/hal.c
hal/armv7a/imx6ull/imx6ull.c
hal/armv7a/imx6ull/imx6ull.h
hal/armv7m/cpu.c
hal/armv7m/cpu.h
hal/armv7m/exceptions.c
hal/armv7m/imxrt/hal.c
hal/armv7m/stm32/hal.c
hal/armv8m/cpu.c
hal/armv8m/cpu.h
hal/armv8m/nrf/hal.c
hal/ia32/exceptions.c
hal/sparcv8leon3/cpu.c
hal/sparcv8leon3/cpu.h
hal/sparcv8leon3/exceptions.c

JIRA: RTOS-489
We want to reset on exception when not DEBUG

armv7m: fix DEBUG reset on exception logic

---

hal/armv7a/imx6ull/_init.S
hal/armv7a/imx6ull/imx6ull.c

The reason for the removal is that support for the `older iMX6UL` has been replaced by the `newer iMX6ULL`. The code related to the older processor has become dead.
Similarly in kernel [phoenix-rtos-kernel/pull/416](https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/416)
JIRA: RTOS-519

remove iMX6UL dead code

---

devices/flash-flexspi/Makefile
devices/flash-flexspi/flashdrv.c
devices/flash-flexspi/fspi/fspi.c
hal/armv7m/exceptions.c

The reason for this is a recent change to phoenix-rtos-build which provides __TARGET and __CPU globally. So local definition of IMXRT* became redundant.
https://github.com/phoenix-rtos/plo/pull/270

Adjust TARGET selection to global CPU defines

---

devices/flash-flexspi/Makefile
hal/armv7a/Makefile
hal/armv7a/imx6ull/Makefile
hal/armv7a/zynq7000/Makefile
hal/armv7m/Makefile
hal/armv7m/imxrt/10xx/Makefile
hal/armv7m/imxrt/117x/Makefile
hal/armv7m/imxrt/Makefile
hal/armv7m/stm32/l4/Makefile
hal/armv8m/Makefile
hal/armv8m/nrf/91/Makefile
hal/ia32/efi/Makefile

Changes indentation `tabs` to `spaces`, so they don't conflict with the `recipe prefix` and unifies the style of variable setting/assignment.
JIRA: RTOS-575

makes: change indentation to spaces

---

hal/armv7m/imxrt/10xx/console.c
hal/armv7m/imxrt/117x/console.c

This change adds an ALTMODE selector depending on the TX_PIN & RX_PIN mux provided in the board config.
JIRA: NIL-459

imxrt: add mux selector in early console

---

hal/armv7m/imxrt/117x/imxrt.c
hal/armv7m/imxrt/117x/imxrt.h

Adds functions, similar to imxrt10xx API, which allow to configure, gpio direction and control gpio: get, set, clear gpio value, either single bit or whole register.
The goal is abbility to provide project `plo_custom.c`, e.g:
```C
#include "imxrt.h"
void hal_customInit(void)
{
/* deassert /RESET of other device */
_imxrt_setIOmux(pctl_mux_gpio_sd_b1_00, 0, 10);
_imxrt_setIOpad(pctl_pad_gpio_sd_b1_00, 0, 0, 0, 0, 0, 0);
_imxrt_gpioConfig(gpio10, 3, 1);
_imxrt_gpioSet(gpio10, 3, 0);
}
```
JIRA: NIL-460

imxrt117x: add functions to control gpio

---

devices/flash-zynq7000/flashcfg.c
devices/flash-zynq7000/flashcfg.h
devices/flash-zynq7000/flashdrv.c
devices/flash-zynq7000/qspi.c
hal/armv7a/zynq7000/Makefile

Initialize configuration registers on flash memories so that we send proper amount of dummy cycles for the frequency we operate at.
Add workaournd to bug in zynq hardware.
Rewrite qspi_polledTransfer to improve readability.
Switch to faster command for page program and read.
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/406

zynq7000-flash: initialize configuration registers

---

devices/flash-imxrt/fspi/fspi.c

The purpose of this PR:
* reduce the size of functions relocated to the itcm memory
* eliminate the problem of byte by byte reading (when a plo is reading its scripts) and the destination address is not necessarily aligned to 32 bits (tfdr and rfdr size). Reading and writing from/to memory is performed in 64bit chunks, which results from the alignment of watermark indicator.
JIRA: RTOS-605
Trying to fix https://github.com/phoenix-rtos/phoenix-rtos-project/issues/773
Since the problem appears once every few hundred launches, it is necessary to run a dedicated testing campaign on rt1064 to check whether the bug has been fixed by this PR.

flash-imxrt: rewrite opRead and opWrite

---

devices/flash-imxrt/nor/nor.c
devices/flash-imxrt/nor/nor_lut.h

Winbond W25Q256* require 4 byte addressing to access addresses beyond 128MBit.
JIRA: RTOS-661

flash-imxrt: fix addressing mode for W25Q256 chip

---

hal/ia32/Makefile
hal/ia32/acpi.c
hal/ia32/acpi.h
hal/ia32/memory.c
syspage.c

Kernel needs ACPI for more advanced features. This PR gives the kernel access to MADT and FADT tables.

hal/ia32: Add basic ACPI support

---

devices/uart-gr716/Makefile
devices/uart-grlib/Makefile
devices/uart-grlib/uart.c
hal/sparcv8leon3/gr716/Makefile

changes to support gr716-mimas

---

hal/armv7a/imx6ull/interrupts.c
hal/armv7a/zynq7000/interrupts.c

Fixes code trying to read from a write-only register.
On both of these platforms interrupt handling code tried to read from EOIR. According to documentation ([link](https://developer.arm.com/documentation/ihi0048/latest/), Table 4-2) EOIR is write-only, reads from it are undefined. The code worked because reads from it probably returned 0.

hal/zynq7000, hal/imx6ull: Fix accesses to GIC EOIR register

---

devices/flash-gr712rc/flashdrv.c
hal/sparcv8leon3/gaisler/gr712rc/Makefile
hal/sparcv8leon3/gaisler/gr712rc/_init.S

JIRA: RTOS-616
This PR:
- updates the flash mode to read in the flashdrv_done function - this ensures that other cores can safely start from flash.
- adapts the initialization process to support multicore systems and copies the PLO to RAM if needed

GR712RC: flashdrv and init fixes

---

devices/uart-grlib/uart.c

JIRA: RTOS-704
allow specifying different `UART_MAX_CNT`

uart-grlib: remove explicit array size declaration

---

hal/armv7m/imxrt/117x/imxrt.c
hal/armv7m/imxrt/117x/imxrt.h
hal/armv7m/imxrt/117x/timer.c

This pull-request implements i.MX RT117x root clock tree configuration.
By default ARM PLL is set to `800MHz` (automotive and industrial targets). For consumer electronics market ARM PLL of M7 CPU is configured to `1GHz`. 
JIRA: RTOS-608

imxrt117x: implement clock root tree

---

cmds/alias.c

DONE: RTOS-713
**OPTIONAL** - to be determined whether we want this or not

alias: Add option to use relative alias offset

---

.codespell_ignore
cmds/elf.h
cmds/kernel.c
devices/ram-storage/ramdrv.c
devices/tty-spike/Makefile
devices/tty-spike/tty-spike.c
devices/uart-16550/uarthw-riscv.c
hal/riscv64/Makefile
hal/riscv64/_init.S
hal/riscv64/_interrupts.S
hal/riscv64/_string.S
hal/riscv64/console.c
hal/riscv64/cpu.h
hal/riscv64/dtb.c
hal/riscv64/dtb.h
hal/riscv64/exceptions.c
hal/riscv64/generic/Makefile
hal/riscv64/generic/config.h
hal/riscv64/generic/hal.c
hal/riscv64/generic/peripherals.h
hal/riscv64/generic/types.h
hal/riscv64/interrupts.c
hal/riscv64/plic.c
hal/riscv64/plic.h
hal/riscv64/sbi.c
hal/riscv64/sbi.h
hal/riscv64/string.c
hal/riscv64/timer.c
ld/common/plo-riscv64.lds
ld/riscv64-generic.ldt

Add plo for riscv64

---

hal/ia32/acpi.c

Required to handle ECAM access for PCIexpress.
before merge:
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/530
JIRA: RTOS-800
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/530

ia32/acpi: add MCFG table handler

---

devices/flash-imxrt/nor/nor.c
devices/flash-imxrt/nor/nor_mx.c

Adds `IS25LP256` and `IS25WP256` flash chips to the supported devices, these chips supports quad lane communication only when appropriate bit (Quad Enable) is set in non-volatile config register, by default only Single and Dual is supported `IO0`, `IO2` and `WP#`,`HOLD#/RESET#` pins are enabled, switching to Quad SPI enables `IO2` and `IO3` instead of `WP#`,`HOLD#/RESET#` pins.
Chip operates at 133MHz clock, same for the rest chips used with i.MX RT117x/10xx, verified to work at 166MHz (but we don't have laboratory tests regarding EMI for 166MHz, so I leave it with 133MHz clock).
JIRA: NIL-539

imxrt-flash: Add IS25LP256 NOR flash support

---

cmds/call.c

The modification causes further processing of the script to stop when the `\0` character terminating the plo script is found.
JIRA: RTOS-827

cmds/call: stop script processing on '\0'

---

devices/flash-imxrt/flashdrv.c
devices/flash-imxrt/fspi/fspi.c
devices/flash-imxrt/fspi/fspi_rt106x.h
devices/flash-imxrt/fspi/fspi_rt117x.h
devices/flash-imxrt/nor/nor.c
hal/armv7m/imxrt/10xx/105x/peripherals.h
hal/armv7m/imxrt/10xx/106x/peripherals.h
hal/armv7m/imxrt/117x/peripherals.h

- probe second flash memory on port B1
- set FLEXSPI2 clock to 132 MHz
- initial flash size fix
- flexspi_getAddressByPort() fix
- change FLEXSPI1 SS0 pin on port B1 to SD_B1_4 (SD_B2_05 is already used for DQS on port A1)
- fix _imxrt_setIOmux() parameters (mode and sion were switched)
- code style changes
JIRA: NIL-570

imxrt-flash/imxrt117x: enable second flash memory & bug fixes

---

devices/flash-imxrt/fspi/fspi_rt117x.h

Currently, we cannot use memory in octo-lane mode (in any existing project and including MIMXRT1170 evalkit) on the B1 bus. Using the FlexSPI2 B1 bus in internal project turns on the pins for the D4-D7 lines which are dangling/unconected and may pickup interference (EMI). This change disables the ability to use octo-lane memory on the B1 line, but leaves the possibility of using this type of memory in octo-lane mode on the B2 bus.
JIRA: NIL-539

imxrt-flash/rt1176: disable octobus on B1 but not B2

---

cmds/Makefile
cmds/app.c
cmds/blob.c
hal/armv7a/imx6ull/Makefile
hal/armv7a/zynq7000/Makefile
hal/armv7m/imxrt/10xx/105x/Makefile
hal/armv7m/imxrt/10xx/106x/Makefile
hal/armv7m/imxrt/117x/Makefile
hal/armv7m/stm32/l4/Makefile
hal/armv8m/nrf/91/Makefile
hal/ia32/Makefile
hal/riscv64/generic/Makefile
hal/sparcv8leon3/gaisler/gr712rc/Makefile
hal/sparcv8leon3/gaisler/gr716/Makefile

This command allows to pass any binary blob to the kernel as a syspage program. Kernel might be unable to execute it of course, but it will not try to, unless asked to do it (i.e. -x flag is not present for blob in the syspage).
Blob can be placed in any memory map, it will be copied by the plo to the destination map, if source != dest.
DONE: NIL-571
Building scripts need modification for this cmd to be usable. Example modification:
```
diff --git a/_targets/build.common b/_targets/build.common
index 2ddc966..2318bb1 100644
--- a/_targets/build.common
+++ b/_targets/build.common
@@ -69,6 +69,14 @@ b_mkscript_user() {
((poffs+=(psz + SIZE_PAGE - 1) & PAGE_MASK))
printf "%s\n" "$cmd";;
+                               blob)
+                                       name=${args[2]%%;*}
+ …
```

cmd: Add blob command

---

hal/armv7a/zynq7000/_init.S
hal/armv7a/zynq7000/hal.c

This change allows all CPU cores to jump into kernel on zynq7000 (both real hardware and QEMU).
The procedure of starting other CPU cores on zynq7000 is substantially different on QEMU and real hardware. On QEMU both cores jump to start of PLO code. On real hardware boot ROM parks CPU 1 in a small bit of code in high OCRAM that monitors memory address `0xfffffff0` and sleeps using `wfe`. In order to achieve the same behavior on QEMU code was added into `_init.S` that parks all other CPU cores in the same fashion.
After change CPU 0 signals other cores that they should jump to kernel before jumping to kernel itself.
Required to allow use of SMP kernel on zynq7000.

zynq7000: initialize all CPUs

---

cmds/kernel.c
hal/riscv64/_init.S
hal/riscv64/cpu.h
hal/riscv64/generic/hal.c
hal/riscv64/interrupts.c
hal/riscv64/plic.c
hal/riscv64/plic.h
hal/riscv64/timer.c

Adapt initialization code, save boot hart ID in syspage, remove timer interrupts.
Needs changes in kernel to work

riscv64: adapt PLO to multicore

---

devices/flash-imxrt/Makefile
devices/flash-imxrt/flashdrv.c
devices/flash-imxrt/fspi.h
devices/flash-imxrt/fspi/fspi.c
devices/flash-imxrt/fspi/fspi_rt105x.h
devices/flash-imxrt/fspi/fspi_rt106x.h
devices/flash-imxrt/fspi/fspi_rt117x.h
devices/flash-imxrt/nor/flash.h
devices/flash-imxrt/nor/nor.c
devices/flash-imxrt/nor/nor.h
devices/flash-imxrt/nor/nor_issi.c
devices/flash-imxrt/nor/nor_lut.h
hal/armv7m/imxrt/10xx/105x/_init.S
hal/armv7m/imxrt/10xx/106x/_init.S
hal/armv7m/imxrt/117x/_init.S

ISSI NOR chips use selecteble dummy cycles to support fast read command. For 133 MHz fast read should include 11 dummy cycles (default is 6). To set correct number of dummy cycles:
- FCFB and flexspi_init() use 60 MHz clock and normal read
- add custom ISSI commands and nor_issiInit()
- add flexspi_postinit() which switches to final 133 MHz clock
DONE: RTOS-128

imxrt-flash: fast read fix for ISSI NOR flash

---

devices/flash-mcxn94x/Makefile
devices/flash-mcxn94x/flash.c
devices/uart-mcxn94x/Makefile
devices/uart-mcxn94x/uart.c
hal/armv8m/Makefile
hal/armv8m/interrupts.c
hal/armv8m/mcx/Makefile
hal/armv8m/mcx/hal.c
hal/armv8m/mcx/n94x/Makefile
hal/armv8m/mcx/n94x/_init.S
hal/armv8m/mcx/n94x/config.h
hal/armv8m/mcx/n94x/console.c
hal/armv8m/mcx/n94x/n94x.c
hal/armv8m/mcx/n94x/n94x.h
hal/armv8m/mcx/n94x/peripherals.h
hal/armv8m/mcx/n94x/timer.c
hal/armv8m/mcx/types.h
ld/armv8m33-mcxn94x.ldt

JIRA: RTOS-881
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1120
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/222
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/569
https://github.com/phoenix-rtos/phoenix-rtos-hostutils/pull/55
https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/132
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/508
https://github.com/phoenix-rtos/phoenix-rtos-build/pull/195
https://github.com/phoenix-rtos/libphoenix/pull/371

armv8m: Add MCX N94x target

---

hal/riscv64/_interrupts.S
hal/riscv64/exceptions.c

RISC-V Privileged Architectures V1.10 renamed and generalized sbadaddr to stval. binutils >= 2.43 dropped support for sbadaddr alias.
JIRA: RTOS-913

riscv: rename sbadaddr to stval

---

cmds/alias.c

Relative base alias simplifies complex script call chains (calling "relative" script from "relative" script is easy).
Please note that relative offset might be negative.
JIRA: NIL-550

cmds/alias: add relative base address support

---

hal/armv7m/imxrt/10xx/105x/_init.S
hal/armv7m/imxrt/10xx/106x/_init.S
hal/armv7m/imxrt/117x/_init.S
ld/armv7m7-imxrt105x.ldt
ld/armv7m7-imxrt106x.ldt
ld/armv7m7-imxrt117x.ldt

This change fixes a boot failure when plo image is larger than the hardcoded value in sflashA1Size, but smaller than m_flash size (the linker does not abort). Now (initial) flash size is tied to FlexSPI Configuration Block so that this never happens again. If plo grows too much, the linker will produce an error.
JIRA: RTOS-920

hal/imxrt: Fix boot from FlexSPI failing

---

devices/tty-bios/tty-bios.c
devices/uart-16550/uarthw-pc.c
hal/ia32/console-serial.c
hal/ia32/console-vga.c
hal/ia32/cpu.c
hal/ia32/cpu.h
hal/ia32/efi/kernel/cpu.h
hal/ia32/interrupts.c
hal/ia32/memory.c
hal/ia32/pci.c

Copy "in" related function from efi.
Newer binutils versions check closely if asm instructions get operands of correct size.
JIRA: RTOS-912

hal/ia32: cast operands to correct sizes

---

devices/flash-gr712rc/flashdrv.c
devices/flash-mcxn94x/flash.c
devices/flash-mps3an536/flashdrv.c
devices/uart-cmsdk-apb/uart.c
devices/uart-mcxn94x/uart.c

This fixes building of recently added devices (from e.g. https://github.com/phoenix-rtos/plo/pull/337) which were merged before merging https://github.com/phoenix-rtos/plo/pull/315 (which did not cover these devices).
JIRA: RTOS-930

devices: fix building of new devices (gr712rc, mcxn94x, ...)

---

devices/pipe-rtt/rtt.c
hal/armv7m/imxrt/10xx/105x/Makefile
hal/armv7m/imxrt/10xx/106x/peripherals.h
hal/armv7m/imxrt/117x/peripherals.h
hal/armv7m/imxrt/hal.c
hal/armv7m/stm32/hal.c
ld/armv7m4-stm32l4x6.ldt
ld/armv7m7-imxrt105x.ldt
ld/armv7m7-imxrt106x.ldt
ld/armv7m7-imxrt117x.ldt
ld/common/plo-rtt.lds

Corrected memory mappings for imxrt devices, which could result in data being placed out of bounds of dtcm memory.
Added support for passing RTT details through syspage on imxrt.
Reserved dedicated memory for RTT in memory maps.
This allows RTT buffers to be allocated at compile time and remain available after kernel is started. This also removes hard-coded RTT address, which reduces confusion when using different memory configurations.

rtt: Improve buffer allocation and handling

---

hal/armv7m/imxrt/hal.c

Missing map entires could cause PLO being overwritten by apps it loads when booted from RAM.
JIRA: RTOS-935

hal/imxrt: add missing map entries

---

_startc.c
devices/flash-imx6ull/nor/nor.c
devices/flash-imx6ull/qspi/qspi.c
devices/flash-imxrt/fspi/fspi_rt105x.h
devices/flash-imxrt/fspi/fspi_rt106x.h
devices/flash-imxrt/fspi/fspi_rt117x.h
devices/uart-imxrt106x/uart.c
hal/armv7m/cpu.c
hal/armv7m/cpu.h
hal/armv7m/imxrt/10xx/console.c
hal/armv7m/imxrt/117x/console.c
hal/armv7m/string.c
lib/cbuffer.c
lib/cbuffer.h

JIRA: RTOS-936
imxrt-106x didn't add map entries for text, rodata, init, init_array, fini_array etc in what could have caused memory overrides if PLO was executed from RAM. (those entries got added on STM32 in https://github.com/phoenix-rtos/plo/pull/197)
imxrt used `.noxip` section for code that should be executed from XIP, however those functions called some function residing in `.text` what make `.noxip` faulty.

imxrt: fix .noxip code calling functions from .text

---

hal/armv7m/imxrt/10xx/106x/imxrt.c

- fix clk0 enable bit of enet PLL
- add bypass during clock frequency change
- initialize enet PLL
- remove enet PLL deinitialization
enet driver for imxrt106x-evk needs this 
Related: [https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/601](https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/601) and [https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/595](https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/595)

hal/imxrt106x: init enet PLL

---

cmds/console.c
hal/armv7m/imxrt/10xx/console.c
hal/armv7m/imxrt/117x/console.c
hal/armv7m/imxrt/hal.c
hal/armv7m/stm32/hal.c
hal/armv7m/stm32/l4/console.c
hal/armv7m/stm32/l4/peripherals.h
lib/console.c
lib/helpers.h

Currently RTT is available as a plo device and also mirrors UART output via hooks. This change makes it possible to replace UART completely by RTT - just define `UART_CONSOLE_PLO` as empty and keep RTT_ENABLED_PLO truthy (enabled by default).
A print is moved from `lib_consoleSet()` to console command to avoid output before the first plo log ("Phoenix-RTOS loader ...").
JIRA: RTOS-754

hal/armv7m: Support RTT as an early console

---

devices/pipe-rtt/device.c

This change fixes the problem of plo's `wait` command not waiting while using RTT console. Read operation was completed immediately instead of blocking for at least `timeout`.
JIRA: NIL-596

devices/pipe-rtt: Properly handle timeout in RTT reads

---

hal/armv7m/imxrt/117x/imxrt.c

properly set the ranges of gpio pad registers that are controlled differently to the rest
Needed for platformctl to work as intended on iMX RT1170-evk.
related change: https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/610

hal/imxrt117x: fix IOpad set

---

hal/armv7m/mpu.c

Use MPU region overlap feature to allow for more granularity when translating memory maps to MPU regions.
On armv7m, the MPU only supports regions if their size is a power of 2 and they are aligned to their size. Additionally, each region is divided into 8 equally sized subregions which can be enabled individually. Memory maps passed using `map` command must be translated into one or more MPU regions so that memory protection can be enforced.
In practice this means that the start and end address representable with one region can have up to 3 "significant bits" - for example, an address range `0x20000 - 0x20500` can be represented with a single region, but range `0x20000 - 0x20900` requires 2 regions. Currently our code will limit assigning regions to 2 per map, which means that attempting …

hal/armv7m: allow for more granular memory maps

---

hal/armv7m/imxrt/117x/imxrt.c

- properly set ranges of registers configured differently
- add a way of setting ODE field in non-LPSR/SNVS GPIO registers
- set proper ranges for setting ODE field in LPSR, SNVS, and remaining GPIO registers
related: https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/618

hal/imxrt117x: fix IOpad

---

Makefile
_startc.c
hal/ia32/acpi.c
riscv-sbi/Makefile

misc: adapt to gcc 14.2

---

devices/flash-ftmctrl/amd-flash.c

JIRA: RTOS-927
disable false positive GCC check.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104657
```
/src/plo/devices/flash-ftmctrl/amd-flash.c: In function 'amd_statusClear':
/src/plo/devices/flash-ftmctrl/amd-flash.c:50:9: warning: array subscript 0 is outside array bounds of 'volatile vu8[0]' {aka 'volatile unsigned char[]'} [-Warray-bounds=]
50 |         *(vu8 *)(ADDR_FLASH + 0x0aaa) = AMD_CMD_CLR_STATUS;
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: note: source object is likely at address zero
```

flash-ftmctrl: disable faulty array bounds check

---

devices/uart-zynq/uart.c

Changes:
- fixed an error I made after testing solution, but before PR was accepted (wrong comparison in conditional macro)
- added wait until RX FIFO is empty - it looks like real trash data can fill entire RX FIFO and without wait until it is empty it does stops our board in bootloader
- see register field description on screenshot below

zynqmp: fix UART RX cleanup

---

hal/armv8m/cpu.h
hal/armv8m/mcx/hal.c
hal/armv8m/mcx/n94x/_init.S
hal/armv8m/mcx/n94x/n94x.c

MCXN94x: Allow running Phoenix-RTOS on CPU1

---

syspage.c
syspage.h

Change HAS_GRAPHICS macro checking to rely on definition of those instead of defined value. With this approach warning stopped to be raised, when enable -Wundef flag
There are some useful warning flags, which are enabled in internal projects, like `-Wundef` and `-Wshadow`.
This commit allow plo to be build with `-Wundef` without warnings
To enable `-Wundef` flag in the future

syspage: Improve HAS_GRAPHICS macro checking
